### ISSUE TITLE
Bump to GMT 6.2.0rc2

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1289]
The second release candidate for GMT 6.2.0 has been released (https://github.com/GenericMappingTools/gmt/releases/tag/6.2.0rc2) on 25 May 2021 and is installable from the [conda-forge devel channel](https://anaconda.org/conda-forge/gmt/files) using the following command:

```
conda install -c conda-forge/label/dev gmt=6.2.0rc2
```

TODO:

- [x] Bump the GMT version to 6.2.0rc2 used in the CI tests (#1290)
- [x] Fix failing tests, mostly those documented in https://github.com/GenericMappingTools/pygmt/issues/1242#issuecomment-830461093
  - [x] test_basemap.py (1) (#1291)
  - [x] test_subplot.py (4) (#1291)
  - [x] test_text.py (18) (#1292)
  - [x] test_wiggle.py (1) (#1291)
- [x] Remove [xfail](https://docs.pytest.org/en/stable/skipping.html#xfail-mark-test-functions-as-expected-to-fail) pytest markers on tests that are now xpass
  - ~~test_grdtrack.py?~~ (tests still fail on macOS/Windows so don't remove the xfail, see #1309)
  - [x] test_grdimage.py (#1296)
  - [ ] test_makecpt.py ()
  - [x] test_solar.py (#1297, #1305)
  - [x] test_velo.py (#1297)
- [x] Add some new tests for [upstream bugs](https://github.com/GenericMappingTools/pygmt/labels/upstream) that were fixed in 6.2.0rc2 (if any)
  - [x] #732?

Supersedes #1217

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
>     * [ ]  Fix failing tests, mostly those documented in [#1242 (comment)](https://github.com/GenericMappingTools/pygmt/issues/1242#issuecomment-830461093)
>       
>       * [ ]  test_basemap.py (1)
>       * [ ]  test_subplot.py (4)
>       * [ ]  test_text.py (18)
>       * [ ]  test_wiggle.py (1)

Instead of opening 4 separate PRs for each of these, how about making just 2? I.e. one for `basemap`/`subplot`/`wiggle`, and one for `text`? Do people have any preference?

**Comment by seisman** [comment]
> > * [ ]   Fix failing tests, mostly those documented in [#1242 (comment)](https://github.com/GenericMappingTools/pygmt/issues/1242#issuecomment-830461093)
> >   
> >   * [ ]   test_basemap.py (1)
> >   * [ ]   test_subplot.py (4)
> >   * [ ]   test_text.py (18)
> >   * [ ]   test_wiggle.py (1)
> 
> Instead of opening 4 separate PRs for each of these, how about making just 2? I.e. one for `basemap`/`subplot`/`wiggle`, and one for `text`? Do people have any preference?

Sounds good to me.

**Comment by seisman** [comment]
Here is a minimal example to reproduce the flaky tests in `test_makecpt.py`. In this example, three figures are generated. The 1st and the 3rd figure uses the same code, so we expect `makecpt1.eps` and `makecpt2.eps` are the same, but actually these two images are slightly different. However, if we remove the code for the 2nd figure, `makecpt1.eps` and `makecpt2.eps` are the same again.

I think it may mean that the settings for each "figure" are not fully isolated and it looks an upstream GMT issue.
```python
import pygmt

fig = pygmt.Figure()
pygmt.makecpt(cmap="categorical", categorical=True)
fig.colorbar(cmap=True, region=[10, 70, -5, 10], frame=True, position="JBC", V=True)
fig.savefig("makecpt1.eps")

fig = pygmt.Figure()
fig.coast(region=[0, 10, -20, -10], projection="M6i",  frame=True, land="black")
fig.savefig("other.eps")

fig = pygmt.Figure()
pygmt.makecpt(cmap="categorical", categorical=True)
fig.colorbar(cmap=True, region=[10, 70, -5, 10], frame=True, position="JBC", V=True)
fig.savefig("makecpt2.eps")
```
@PaulWessel @meghanrjones Please see if the above example can help you debug GMT.

**Comment by seisman** [comment]
A bash version to reproduce the issue:
```
gmt begin

gmt figure makecpt1 pdf
gmt makecpt -Ccategorical -W
gmt colorbar -C -R10/70/-5/10 -B -DJBC

gmt figure other pdf
gmt coast -R0/10/-20/-10 -JM6i -B -Gblack

gmt figure makecpt2 pdf
gmt makecpt -Ccategorical -W
gmt colorbar -C -R10/70/-5/10 -B -DJBC

gmt end
```

**Comment by seisman** [comment]
The "makecpt" flaky tests will be fixed in https://github.com/GenericMappingTools/gmt/pull/5280 and available in GMT 6.2.0.

**Comment by weiji14** [comment]
Ok, I'm closing this issue. There's a few more PyGMT tests we'll need to update since there have been bugfixes in upstraem GMT (to be released in GMT 6.2.0 https://github.com/GenericMappingTools/gmt/issues/5290!), but that can be tracked in a separate 'Bump to GMT 6.2.0' issue :grin:

- [ ] grdtrack (#1304/#1309)
- [ ] rose (#1315)
- [ ] contour (#1303/#1313)
