### ISSUE TITLE
 Bump to GMT 6.2.0

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#1320]
:tada: GMT 6.2.0 has been released (https://github.com/GenericMappingTools/gmt/releases/tag/6.2.0) on 6 June 2021! It is installable from the [conda-forge channel](https://anaconda.org/conda-forge/gmt/files) using the following command:

```
conda install -c conda-forge gmt=6.2.0
```

TODO:

- [x] Bump the minimum required GMT version to 6.2.0 (#1321, @weiji14)
- [x] Fix failing tests (recommend opening 2 PRs, one for `rose` and one for the others).
  - [x] test_colorbar (1), test_inset (2), test_legend (1), test_logo (1) (#1322, @weiji14)
  - ~~test_plot3d (1)~~ (only broken on Windows, see https://github.com/GenericMappingTools/pygmt/pull/1322#discussion_r646112259)
  - [x] test_rose (5, #1315, #1324, @michaelgrund)
- [x] Remove [xfail](https://docs.pytest.org/en/stable/skipping.html#xfail-mark-test-functions-as-expected-to-fail) pytest markers on tests that are now xpass
  - [x] grdtrack (#1309, #1304, @seisman)
  - [x] makecpt (#1323 @seisman)

Supersedes #1289

**Are you willing to help implement and maintain this feature?** Yes
