### ISSUE TITLE
ESWN: Add common options to PyGMT functions and methods

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1445]
**Description of the desired feature**

There are some common options from GMT that are missing from the corresponding PyGMT functions and methods. This issue tracks adding the common options to the following methods:

- [x] [pygmt.Figure.contour](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/contour.py)  @michaelgrund (#1446) 
     - U - timestamp
     - b - binary
     - d - nodata
     - e - find
     - f - coltypes
     - h - header
- [x] [pygmt.Figure.grdview](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/grdview.py) @arleaman (#1450)
     - n - interpolation
- [x] [pygmt.Figure.histogram](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/histogram.py) @beckysalvage (#1451)
     - b - binary
     - d - nodata
     - e - find
     - g - gap
     - h - header
     - w - wrap
- [x] [pygmt.Figure.image](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/image.py) @daroari (#1449)
     - U - timestamp
- [x] [pymgt.Figure.legend](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/legend.py) @obaney (#1453)
     - U - timestamp
- [x] [pygmt.Figure.plot](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/plot.py) @michaelgrund (#1502) 
     - b - binary
     - d - nodata
     - e - find
     - g - gap
     - h - header
     - w - wrap
- [x] [pygmt.Figure.plot3d](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/plot3d.py) @michaelgrund (#1503) 
     - b - binary
     - d - nodata
     - e - find
     - f - coltypes
     - g - gap
     - h - header
     - w - wrap
- [x] [pygmt.Figure.rose](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/rose.py) @srijac (#1452)
     - b - binary
     - d - nodata
     - e - find
     - g - gap
     - h - header
     - w - wrap
- [x] [pygmt.Figure.text](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/text.py) @meghanrjones (#1448)
     - U - timestamp
     - a - aspatial
     - e - find
     - h - header
     - w - wrap
- [x] [pygmt.Figure.velo](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/velo.py) @michaelgrund (#1497 ) 
     - d - nodata
     - e - find
     - h - header
     - i - incols
- [x] [pymgt.Figure.wiggle](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/wiggle.py) @michaelgrund (#1498) 
     - f - coltypes
     - t - transparency
     - w - wrap
- [x] [pygmt.grdtrack](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/grdtrack.py) @michaelgrund (#1499) 
    - b - binary
    - d - nodata
    - e - find
    - g - gap
    - h - header
    - o - outcols
    - s - skiprows
    - w - wrap
- [x] [pygmt.blockmean](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/blockm.py) and [pygmt.Figure.blockmedian](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/blockm.py) @michaelgrund (#1500) 
     - d - nodata
     - e - find
     - h - header
- [x] [pygmt.surface](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/src/surface.py) @michaelgrund (#1501)
     - b - binary
     - d - nodata
     - e - find
     - h - header
     - i - incols
     - s - skiprows

**Are you willing to help implement and maintain this feature?** Glad to help people with PRs!

**Comment by meghanrjones** [comment]
@michaelgrund, thanks for submitting the PR! I'm going to guide the participants in the ESWN workshop tomorrow through the remainder of the tasks (i.e. adding the other common options), and it will be helpful for them to use your PR as an example!

**Comment by michaelgrund** [comment]
Great idea @meghanrjones 👍.

**Comment by meghanrjones** [comment]
@michaelgrund FYI I just unassigned plot/plot3d from the workshop list if you want to wrap this issue up (no pressure though).

**Comment by meghanrjones** [comment]
I forgot to include instructions for updating the `kwargs_to_strings` with the addition of `g` and `o`. I will submit a single PR fixing this, which should be the end of this issue.
