### ISSUE TITLE
Bump to GMT 6.3.0

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1644]
:tada: [GMT 6.3.0](https://github.com/GenericMappingTools/gmt/releases/tag/6.3.0) has been released! It is installable from the [conda-forge channel](https://anaconda.org/conda-forge/gmt/files) using the following command:

`conda install -c conda-forge gmt=6.3.0`

**To-Do**:
- [x] Bump the minimum required GMT version (@meghanrjones - https://github.com/GenericMappingTools/pygmt/pull/1649)
  - [x] Update `.github/workflows/cache_data.yaml` 
  - [x] Update `.github/workflows/ci_docs.yml`
  - [x] Update `.github/workflows/ci_tests.yaml`
  - [x] Update `doc/install.rst`
  - [x] Update `environment.yml`
  - [x] Update `required_version` in `pygmt/clib/session.py`
  - [x] Update `test_get_default` in `pygmt/tests/test_clib.py`
  - [x] Update compatibility table in `README.rst`
- [x] Fix failing tests (1 or more PRs)
  - [x] `pygmt/tests/test_basemap.py::test_basemap_rose` @weiji14 #1658
  - [x] `pygmt/tests/test_basemap.py::test_basemap_compass` @weiji14 #1658
  - [x] `pygmt/tests/test_inset.py::test_inset_context_manager` @meghanrjones https://github.com/GenericMappingTools/pygmt/pull/1653
  - [x] `pygmt/tests/test_legend.py::test_legend_specfile` @meghanrjones https://github.com/GenericMappingTools/pygmt/pull/1654
  - [x] `pygmt/tests/test_rose.py::test_rose_bools` @meghanrjones https://github.com/GenericMappingTools/pygmt/pull/1655
  - [x] `pygmt/tests/test_rose.py::test_rose_deprecate_columns_to_incols` @meghanrjones https://github.com/GenericMappingTools/pygmt/pull/1655
- [x] Remove [xfail](https://docs.pytest.org/en/stable/skipping.html#xfail-mark-test-functions-as-expected-to-fail) pytest markers on tests that are now xpass (@meghanrjones) https://github.com/GenericMappingTools/pygmt/pull/1656
  - [x] `pygmt/tests/test_grdimage.py::test_grdimage_grid_and_shading_with_xarray[png]` (xref https://github.com/GenericMappingTools/pygmt/issues/618#issuecomment-961579394)
  - [x] `pygmt/tests/test_grdimage.py::test_grdimage_central_meridians_and_standard_parallels[Q-0-0-png]`
  - [x] `pygmt/tests/test_grdimage.py::test_grdimage_central_meridians_and_standard_parallels[Q-0-30-png] `
- [x] Update fixed [xfail](https://docs.pytest.org/en/stable/skipping.html#xfail-mark-test-functions-as-expected-to-fail) tests (@meghanrjones) https://github.com/GenericMappingTools/pygmt/pull/1657
  - [x] `pygmt/tests/test_velo.py::test_velo_pandas_dataframe`
  - [x] `pygmt/tests/test_velo.py::test_velo_numpy_array_numeric_only`
- [x] Add regression tests to catch 'upstream' bugs
  - [x] #1313 (@seisman #1692)
  - [x] #1367
  - [x] #1440 (seisman #1771)
- [x] Update deprecated syntax in source code and examples based on the [GMT Changelog](https://docs.generic-mapping-tools.org/latest/changes.html)
  - [x] Update deprecated **-JG** syntax @michaelgrund #1659 
  - [x] Update deprecated **-g** common option syntax @michaelgrund #1670 
  - [x] Update psconvert **-A** syntax @michaelgrund #1673

**Comment by weiji14** [comment]
Thanks for opening this @meghanrjones! I guess we just put our names next to each task to assign ourselves to it? Do you want to take the first task, and I'll handle some of the tests?

**Comment by meghanrjones** [comment]
> Thanks for opening this @meghanrjones! I guess we just put our names next to each task to assign ourselves to it? Do you want to take the first task, and I'll handle some of the tests?

Yes, editing the issue with our names next to tasks sounds good.

Yes, I can do the first task on Tuesday. If anyone else wants to self-assign before then that's fine too.

**Comment by michaelgrund** [comment]
I can update the deprecated syntax.
