### ISSUE TITLE
Use a static grid, asymmetric region, and xarray.testing for raster tests

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1684]
This issue was originally for discussing improvements to the PyGMT test suite and is now dedicated to tracking specific improvements:

1. Use xarray.testing rather than pygmt.grdinfo
2. Use `static_earth_relief` rather than `earth_relief`
3. Use asymmetric regions to facilitate identification of lat/lon errors

If anyone wants to help, please edit this comment to add your username next to the module or post a comment below to avoid redundant work.

- [x] Add static_earth_relief to cache (https://github.com/GenericMappingTools/gmtserver-admin/pull/139)
- [x] Add function to load static_earth_relief.nc as an xarray.DataArray (#1727)
- [x] test_grd2cpt.py (static_earth_relief) (@willschlitzer #1736)
- [x] test_grd2xyz.py (static_earth_relief) (@willschlitzer #1737)
- [x] test_grdclip.py (xarray.testing) (@meghanrjones, #1573)
- [x] test_grdclip.py (static_earth_relief) (@willschlitzer #1738)
- [x] text_grdcontour.py (static_earth_relief) (@willschlitzer #1741)
- [x] test_grdcut.py (xarray.testing) (@meghanrjones, #1574)
- [x]  test_grdcut.py (static_earth_relief) (@willschlitzer #1742)
- [x] test_grdfill.py (xarray.testing) (@willschlitzer, #1677)
- [x] test_grdfill.py (static_earth_relief) (@willschlitzer #1743)
- [x] test_grdfilter.py (xarray.testing and static_earth_relief) (@willschlitzer, #1678)
- [x] test_grdgradient.py (xarray.testing and static_earth_relief) (@willschlitzer, #1679)
- [x] test_grdinfo.py (static_earth_relief) (@willschlitzer #1746)
- [x] test_grdlandmask.py (xarray.testing) (@willschlitzer, #1680)
- [x] test_grdproject.py (xarray.testing and static_earth_relief) (@willschlitzer #1683)
- [x] test_grdsample.py (xarray.testing and static_earth_relief) (@willschlitzer, #1681)
- [x] test_grdtrack.py (static_earth_relief) (@willschlitzer, #1762)
- [x] test_grdview.py (static_earth_relief) (@willschlitzer #1752)
- [x] test_grdvolume.py (static_earth_relief) (@willschlitzer #1747)
- [x] test_makecpt.py (static_earth_relief) (@willschlitzer #1748)
- [x] test_xyz2grd.py (xarray.testing and static_earth_relief) (@willschlitzer #1682)
- [x] pygmt.clib.session example (static_earth_relief) (@willschlitzer #1761)

**Comment by meghanrjones** [comment]
Thanks @willschlitzer for getting started on these tests! As @weiji14 mentioned in https://github.com/GenericMappingTools/pygmt/issues/593#issuecomment-935295232, we may want to work to address the likely failures due to upcoming `@earth_relief` failures during this process of migrating away from grdinfo. I have a few questions/comments regarding the tests:

1. Should we continue using the `@earth_relief` remote datasets for grid processing/plotting tests at all? We could instead create a xarray.DataArray with a subset of the V2.1 SRTM15+ data using a new helper function (e.g., `pygmt.helpers.testing.static_earth_relief()`. Probably no one wants to write out the data for 360 x 180 grid, so this would require determining whether any of the tests using global grids could use a smaller subset. The tests that use `@earth_relief` are listed below for context. For small grids (10x10), it is ~5% quicker to create a grid than use the remote data and could mean less maintenance work for future SRTM15+ updates.

2. I think we should move away from regions where the latitudes and longitudes could be switched without notice (e.g., `region = [-5, 5, -5, 5]`

2. We may need to adjust the rtol on [assert_allclose](https://xarray.pydata.org/en/stable/generated/xarray.testing.assert_allclose.html) for some tests - I'll post more on this later but accidentally opened this issue before working out the precision factors.

#### Processing/plotting tests using `load_earth_relief`:
*Global pixel registration*
- test_grdcut.py - `load_earth_relief(registration="pixel")`
- test_grd2cpt.py - `load_earth_relief()`
- test_grdfilter.py -` load_earth_relief(registration="pixel”)`

*Global gridline registration*
- test_grdimage.py - `load_earth_relief(registration="gridline")`
- test_grdinfo.py - `load_earth_relief(registration="gridline")`
- test_grdcontour.py - `load_earth_relief(registration="gridline”)`
- test_makecpt.py - `load_earth_relief(registration="gridline”)`

*Symmetric subset*
- test_grdgradient.py - `load_earth_relief(resolution="01d", region=[-5, 5, -5, 5])`
- test_grdproject.py - `load_earth_relief(resolution="01d", region=[-5, 5, -5, 5])`
- test_grdclip.py - `load_earth_relief(resolution="01d", region=[-5, 5, -5, 5]`
- test_grdsample.py - `load_earth_relief(resolution="01d", region=[-5, 5, -5, 5], registration=“pixel”)`

*Other subset*
- test_grd2xyz.py - `load_earth_relief(resolution="01d", region=[-1, 1, 3, 5]`
- test_grdtrack.py - `load_earth_relief(registration="gridline").sel(lat=slice(-49, -42), lon=slice(-118, -107))`
- test_grdvolume.py - `load_earth_relief(resolution="01d", region=[-100, -95, 34, 39])`
- test_grdfill.py - `load_earth_relief(registration="pixel", region=[125, 130, -25, -20])`

**Comment by meghanrjones** [comment]
These are the tests that can be expected to fail after the `@earth_relief` update to V2.3 (n=45):
```
FAILED ../pygmt/clib/session.py::pygmt.clib.session.Session
FAILED ../pygmt/clib/session.py::pygmt.clib.session.Session.virtualfile_from_grid
FAILED ../pygmt/tests/test_datasets_earth_relief.py::test_earth_relief_01d
FAILED ../pygmt/tests/test_datasets_earth_relief.py::test_earth_relief_01d_with_region
FAILED ../pygmt/tests/test_datasets_earth_relief.py::test_earth_relief_30m
FAILED ../pygmt/tests/test_grd2cpt.py::test_grd2cpt
FAILED ../pygmt/tests/test_grdclip.py::test_grdclip_outgrid
FAILED ../pygmt/tests/test_grdclip.py::test_grdclip_no_outgrid
FAILED ../pygmt/tests/test_grdcontour.py::test_grdcontour
FAILED ../pygmt/tests/test_grdcontour.py::test_grdcontour_labels
FAILED ../pygmt/tests/test_grdcontour.py::test_grdcontour_slice
FAILED ../pygmt/tests/test_grdcontour.py::test_grdcontour_file
FAILED ../pygmt/tests/test_grdcontour.py::test_grdcontour_interval_file_full_opts
FAILED ../pygmt/tests/test_grdcut.py::test_grdcut_file_in_file_out
FAILED ../pygmt/tests/test_grdcut.py::test_grdcut_file_in_dataarray_out
FAILED ../pygmt/tests/test_grdcut.py::test_grdcut_dataarray_in_file_out
FAILED ../pygmt/tests/test_grdcut.py::test_grdcut_dataarray_in_dataarray_out
FAILED ../pygmt/tests/test_grdfill.py::test_grdfill_file_out
FAILED ../pygmt/tests/test_grdfilter.py::test_grdfilter_dataarray_in_dataarray_out
FAILED ../pygmt/tests/test_grdfilter.py::test_grdfilter_dataarray_in_file_out
FAILED ../pygmt/tests/test_grdfilter.py::test_grdfilter_file_in_dataarray_out
FAILED ../pygmt/tests/test_grdfilter.py::test_grdfilter_file_in_file_out
FAILED ../pygmt/tests/test_grdgradient.py::test_grdgradient_outgrid
FAILED ../pygmt/tests/test_grdgradient.py::test_grdgradient_no_outgrid
FAILED ../pygmt/tests/test_grdinfo.py::test_grdinfo
FAILED ../pygmt/tests/test_grdinfo.py::test_grdinfo_file
FAILED ../pygmt/tests/test_grdinfo.py::test_grdinfo_region
FAILED ../pygmt/tests/test_grdproject.py::test_grdproject_file_out
FAILED ../pygmt/tests/test_grdproject.py::test_grdproject_no_outgrid
FAILED ../pygmt/tests/test_grdtrack.py::test_grdtrack_input_dataframe_and_dataarray
FAILED ../pygmt/tests/test_grdtrack.py::test_grdtrack_input_csvfile_and_dataarray
FAILED ../pygmt/tests/test_grdtrack.py::test_grdtrack_input_dataframe_and_ncfile
FAILED ../pygmt/tests/test_grdtrack.py::test_grdtrack_input_csvfile_and_ncfile
FAILED ../pygmt/tests/test_grdtrack.py::test_grdtrack_without_outfile_setting
FAILED ../pygmt/tests/test_grdview.py::test_grdview_with_perspective_and_zscale
FAILED ../pygmt/tests/test_grdview.py::test_grdview_with_perspective_and_zsize
FAILED ../pygmt/tests/test_grdview.py::test_grdview_with_cmap_for_perspective_surface_plot
FAILED ../pygmt/tests/test_grdview.py::test_grdview_on_a_plane
FAILED ../pygmt/tests/test_grdview.py::test_grdview_on_a_plane_with_colored_frontal_facade
FAILED ../pygmt/tests/test_grdview.py::test_grdview_with_perspective_and_zaxis_frame
FAILED ../pygmt/tests/test_grdview.py::test_grdview_surface_plot_styled_with_contourpen
FAILED ../pygmt/tests/test_grdview.py::test_grdview_surface_mesh_plot_styled_with_meshpen
FAILED ../pygmt/tests/test_grdview.py::test_grdview_on_a_plane_styled_with_facadepen
FAILED ../pygmt/tests/test_makecpt.py::test_makecpt_truncated_zlow_zhigh
FAILED ../pygmt/tests/test_makecpt.py::test_makecpt_continuous
```

**Comment by willschlitzer** [comment]
I think this is a good idea. Having a standardized grid should make it easier to write tests, and will save us time in the future. If nothing else, we should move grids to be over-land, as I assume land data is less likely to change instead of ocean data.

**Comment by willschlitzer** [comment]
@meghanrjones Should we work to change the `region` arguments for the tests that have symmetric or global regions right now, or wait until the `earth_relief` update comes and we also (hopefully) move to a local xarray file?

**Comment by meghanrjones** [comment]
I think it would be better to update the region at the same as migrating to a locally defined xarray.DataArray to reduce reviewer work. If we chose to use a function that creates a DataArray rather than the remote files, we do not need to wait for the earth_relief update since we can create the grid based on the contents of SRTM15+V2.1.

**Comment by willschlitzer** [comment]
Are we planning on using preset DataArrays rather than grids from `load_earth_relief`? Now that the new Earth relief files have been pushed, it seems like we should decide how this issue will be handled.

**Comment by weiji14** [comment]
I quite like @meghanrjones's idea at https://github.com/GenericMappingTools/pygmt/issues/1684#issuecomment-999823615 to have a `pygmt.helpers.testing.static_earth_relief()` function which could be a near drop-in replacement for existing tests using `pygmt.datasets.load_earth_relief()`. Or at least some function in `pygmt.helpers.testing` which loads a standard grid we can re-use across all tests.

There are some unit tests that run on an actual file (e.g. in test_grdimage.py) rather than an `xarray.DataArray` grid, so I'm thinking whether it's worth caching an `@earth_relief_01d_p_v2.3` file (and possibly the gridline-registered version) at https://github.com/GenericMappingTools/gmtserver-admin/tree/master/cache which `pygmt.helpers.testing.static_earth_relief()` would pull from. Alternatively, we could generate a purely synthetic grid, though I personally prefer testing on semi-real data.

**Comment by meghanrjones** [comment]
> There are some unit tests that run on an actual file (e.g. in test_grdimage.py) rather than an `xarray.DataArray` grid, so I'm thinking whether it's worth caching an `@earth_relief_01d_p_v2.3` file (and possibly the gridline-registered version) at https://github.com/GenericMappingTools/gmtserver-admin/tree/master/cache which `pygmt.helpers.testing.static_earth_relief()` would pull from. Alternatively, we could generate a purely synthetic grid, even though I feel that testing on semi-real data is better.

We could also use @tut_bathy.nc for some tests rather than @earth_relief_01d. It's a bit smaller (11 KB versus 114 KB) and wouldn't require a new cache file.

```
gmt grdinfo @tut_bathy.nc
gmt grdimage @tut_bathy.nc -B -png test
```

```
Title: ETOPO5 global topography
Command: grdreformat -fg bermuda.grd bermuda.nc=ns
Remark: /home/elepaio5/data/grids/etopo5.i2
Gridline node registration used [Geographic grid]
Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
x_min: -66 x_max: -60 x_inc: 0.0833333333333 (5 min) name: Longitude n_columns: 73
y_min: 30 y_max: 35 y_inc: 0.0833333333333 (5 min) name: Latitude n_rows: 61
v_min: -5475 v_max: -89 name: Topography [m]
scale_factor: 1 add_offset: 0
format: classic
Default CPT: 
```
![test](https://user-images.githubusercontent.com/14077947/152247133-c818faaa-ed3e-4a7e-a1aa-8548c5d4f2c8.png)

**Comment by willschlitzer** [comment]
> > There are some unit tests that run on an actual file (e.g. in test_grdimage.py) rather than an `xarray.DataArray` grid, so I'm thinking whether it's worth caching an `@earth_relief_01d_p_v2.3` file (and possibly the gridline-registered version) at https://github.com/GenericMappingTools/gmtserver-admin/tree/master/cache which `pygmt.helpers.testing.static_earth_relief()` would pull from. Alternatively, we could generate a purely synthetic grid, even though I feel that testing on semi-real data is better.
> 
> We could also use @tut_bathy.nc for some tests rather than @earth_relief_01d. It's a bit smaller (11 KB versus 114 KB) and wouldn't require a new cache file.

This still seems like it covers a pretty big area/has a lot of data; wouldn't it speed up our plotting tests more to cache a smaller grid file (something like 10 x10 degree squadre at 30 minute resolution)?

**Comment by weiji14** [comment]
> > > There are some unit tests that run on an actual file (e.g. in test_grdimage.py) rather than an `xarray.DataArray` grid, so I'm thinking whether it's worth caching an `@earth_relief_01d_p_v2.3` file (and possibly the gridline-registered version) at https://github.com/GenericMappingTools/gmtserver-admin/tree/master/cache which `pygmt.helpers.testing.static_earth_relief()` would pull from. Alternatively, we could generate a purely synthetic grid, even though I feel that testing on semi-real data is better.
> > 
> > We could also use @tut_bathy.nc for some tests rather than @earth_relief_01d. It's a bit smaller (11 KB versus 114 KB) and wouldn't require a new cache file.
> 
> This still seems like it covers a pretty big area/has a lot of data; wouldn't it speed up our plotting tests more to cache a smaller grid file (something like 10 x10 degree squadre at 30 minute resolution)?

Ok, how about we make a `pygmt.helpers.testing.static_relief()` based on a subset of the `@tut_bathy.nc`? Further to Meghan's point, we probably want a rectangular sample grid (e.g. 4 x 6 pixels) so that we don't get accidental errors with longitude and latitude mixed up.

**Comment by willschlitzer** [comment]
> > > > There are some unit tests that run on an actual file (e.g. in test_grdimage.py) rather than an `xarray.DataArray` grid, so I'm thinking whether it's worth caching an `@earth_relief_01d_p_v2.3` file (and possibly the gridline-registered version) at https://github.com/GenericMappingTools/gmtserver-admin/tree/master/cache which `pygmt.helpers.testing.static_earth_relief()` would pull from. Alternatively, we could generate a purely synthetic grid, even though I feel that testing on semi-real data is better.
> > > 
> > > 
> > > We could also use @tut_bathy.nc for some tests rather than @earth_relief_01d. It's a bit smaller (11 KB versus 114 KB) and wouldn't require a new cache file.
> > 
> > 
> > This still seems like it covers a pretty big area/has a lot of data; wouldn't it speed up our plotting tests more to cache a smaller grid file (something like 10 x10 degree squadre at 30 minute resolution)?
> 
> Ok, how about we make a `pygmt.helpers.testing.static_relief()` based on a subset of the `@tut_bathy.nc`? Further to Meghan's point, we probably want a rectangular sample grid (e.g. 4 x 6 pixels) so that we don't get accidental errors with longitude and latitude mixed up.

That works for me.

**Comment by meghanrjones** [comment]
I started working on this but it turns out that it's super annoying to create a static DataArray based on a grid with a 0.0833333333333 grid spacing because of the checks in place for irregular grids. Based on this trial, I would prefer to go back to @weiji14's suggestion to add a small file to the cache based on @earth_relief_01d_p V2.3. I could submit a PR to add a file based on `gmt grdcut @earth_relief_01d_p -R-55/-47/-24/-10 -Gstatic_earth_relief.nc` to the cache. The output from this command is 1.6 KB with the following metadata:
```
static_earth_relief.nc: Title: Produced by grdcut
static_earth_relief.nc: Command: grdcut @earth_relief_01d_p -R-55/-47/-24/-10 -Gstatic_earth_relief.nc
static_earth_relief.nc: Remark: Reduced by Gaussian Cartesian filtering (111.2 km fullwidth) from SRTM15_V2.3.nc [Sandwell et al., 2022; https://doi.org/10.1029/2021EA002069]
static_earth_relief.nc: Pixel node registration used [Geographic grid]
static_earth_relief.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
static_earth_relief.nc: x_min: -55 x_max: -47 x_inc: 1 name: longitude n_columns: 8
static_earth_relief.nc: y_min: -24 y_max: -10 y_inc: 1 name: latitude n_rows: 14
static_earth_relief.nc: v_min: 190 v_max: 981 name: elevation (m)
static_earth_relief.nc: scale_factor: 1 add_offset: 0
static_earth_relief.nc: format: classic
static_earth_relief.nc: Default CPT: geo
```

**Comment by willschlitzer** [comment]
@meghanrjones This works for me! Once you submit that file to the cache I'll update the pull requests to not use a DataArray and instead used that cached grid file.

**Comment by seisman** [comment]
@willschlitzer is adding some inline examples in module docstrings (addressing #1686) which access the latest earth relief data by calling the `load_earth_relief` function. Although these inline examples are skipped in tests, some numbers in these examples will be outdated when new earth relief grids are released.

**Comment by willschlitzer** [comment]
> @willschlitzer is adding some inline examples in module docstrings (addressing #1686) which access the latest earth relief data by calling the `load_earth_relief` function. Although these inline examples are skipped in tests, some numbers in these examples will be outdated when new earth relief grids are released.

Should I not be using `load_earth_relief` in the inline examples? I think that's the most accessible way for a new user to get an example grid to use to try a function.

**Comment by willschlitzer** [comment]
@meghanrjones Now that we have a standard file (which I'm assumed is called with `@static_earth_relief`), should we be calling the remote file directly or is the plan to add a function to call it?

**Comment by meghanrjones** [comment]
> @meghanrjones Now that we have a standard file (which I'm assumed is called with `@static_earth_relief`), should we be calling the remote file directly or is the plan to add a function to call it?

We can use `@static_earth_relief` for tests that run on an actual file, but I think we should add this file to `pygmt.datasets.list_sample_data` and `pygmt.datasets.load_sample_data` to return an xarray.DataArray for tests on DataArray input. I could submit a PR for this tomorrow AM, but if you or anyone else has time to add this before then please feel free to do so.

**Comment by meghanrjones** [comment]
FYI I updated the checklist at the start of the issue to include all tests that currently use `earth_relief` except `test_grdimage.py` which requires a global dataset.

**Comment by willschlitzer** [comment]
Why wouldn't we use `# doctest: +SKIP` in the pygmt.clib.session example?

**Comment by meghanrjones** [comment]
> Why wouldn't we use `# doctest: +SKIP` in the pygmt.clib.session example?

The other modules have unit tests in the corresponding `pygmt/tests/test_*.py`, but that method does not have a unit test in test_clib.py

**Comment by willschlitzer** [comment]
I'm trying to rewrite the tests for `grdtrack`. I'm not able to use ocean_ride_points.txt with the static Earth relief grid input. Should we use a different input for `grdtrack`?

**Comment by willschlitzer** [comment]
> FYI I updated the checklist at the start of the issue to include all tests that currently use `earth_relief` except `test_grdimage.py` which requires a global dataset.

Should we rewrite the `grdimage` tests? They have some of the longest test durations; I would assume they could be sped up significantly if we swapped out the grid to use `static_earth_relief`.

**Comment by meghanrjones** [comment]
> > FYI I updated the checklist at the start of the issue to include all tests that currently use `earth_relief` except `test_grdimage.py` which requires a global dataset.
> 
> Should we rewrite the `grdimage` tests? They have some of the longest test durations; I would assume they could be sped up significantly if we swapped out the grid to use `static_earth_relief`.

It may be possible to use `@static_earth_relief.nc` for a few of the grdimage tests, but others are regression tests that require larger areas than in `static_earth_relief`. So it would require going through the issues referenced in each test to determine whether the bug could be reproduced with a smaller region.
