### ISSUE TITLE
More GMT data sources in load_earth_relief and other load_earth functions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1786]
**Description of the desired feature**

GMT now provides earth relief datasets from different data sources:

- [x] `earth_relief`: global earth relief data from SRTM15+ (resolutions from `01d` to `01s`)
- [x] `earth_synbath`: new earth relief data that uses the statistical properties of young seafloor fabric and directions of spreading is also available and provides more realistic relief in areas of young seafloor with small seamounts (resolutions: from `01d` to `01s`) #2162
- [x] `earth-gebco`: earth relief data from GEBCO (resolutions: `01d` to `01s`) #1818
- [x] `earth-gebcosi`: earth relief data from GEBCO but gives sub-ice elevations (resolutions: `01d` to `01s`) #2192

References:

- https://www.generic-mapping-tools.org/remote-datasets/earth-relief.html
- https://www.generic-mapping-tools.org/remote-datasets/earth-gebco.html

Instead of having more `load_earth_xxx` functions, I think we can extend the `load_earth_relief` function by adding a new parameter (for example `subtype` or `data_source`), with possible values: `relief` (default), `synbath`, `gebco`, `gebcosi`.

---

Other non `earth_relief` data sources:

- [x] `earth_age` #1471
- [x] `earth_faa` #2238
- [x] `earth_geoid` #2236
- [x] `earth_vgg` #2240
- [x] `earth_mag` #2196, `earth_mag4km` #2239, `earth_wdmam` #2241
- [x] `earth_mask` (#2312)

**Comment by weiji14** [comment]
Related to https://github.com/GenericMappingTools/pygmt/issues/1442

**Comment by seisman** [comment]
Closing the feature request as it has been implemented in a series of PRs. Thanks @willschlitzer.

**Comment by weiji14** [comment]
Re-opening to track other non earth_relief data sources listed in https://www.generic-mapping-tools.org/remote-datasets (except for the Earth day/night image) as mentioned in https://github.com/GenericMappingTools/pygmt/pull/2272#discussion_r1058472983.

**Comment by willschlitzer** [comment]
@seisman as you mentioned Mars elevation in [this comment](https://github.com/GenericMappingTools/pygmt/pull/2200#discussion_r1038190281), is there a plan to add planetary datasets (Mars/Moon relief data, I'm assuming)?

**Comment by seisman** [comment]
> @seisman as you mentioned Mars elevation in [this comment](https://github.com/GenericMappingTools/pygmt/pull/2200#discussion_r1038190281), is there a plan to add planetary datasets (Mars/Moon relief data, I'm assuming)?

I think there was a proposal to support other planetary datasets but it was not funded. So there is limited resources for adding more datasets, but I believe volunteer are always welcomed.
