### ISSUE TITLE
Release PyGMT v0.6.0

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1801]
**Release**: [v0.6.0](https://github.com/GenericMappingTools/pygmt/milestones/?)
**Scheduled Date**: 2022/03/14
**Pull request due date**: 2022/03/11

**Priority PRs/issues to complete prior to release**
- [x] https://github.com/GenericMappingTools/pygmt/pull/1487
- [x] #1792
- [x] #731 (if possible)
- [x] #1812
- [x] #1719

**Before release**:
- [x] Run `grep --include="*.py" -r 'remove_version="vX.Y.Z"' pygmt` from the base of the repository to check if any deprecations and related tests should be removed in this version
  - [x] Remove parameter "columns", use "incols" instead (#1806)
  - [x] Remove parameter "sizes", use "size" instead (#1809)
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" @weiji14  (10.5281/zenodo.6349217)
- [x] Finish up 'Changelog entry for v0.x.x' Pull Request: (@meghanrjones) #1808
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update `CITATION.cff` and BibTeX at https://github.com/GenericMappingTools/pygmt#citing-pygmt
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#documentation-for-other-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-gmt-and-pythonnumpy-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice ([see maintainers guide for details](https://www.pygmt.org/dev/maintenance.html#updating-the-changelog))

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot] @weiji14 (Remember to bump NEP29 versions!!) https://github.com/conda-forge/pygmt-feedstock/pull/21
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (after conda-forge update) (@meghanrjones https://github.com/GenericMappingTools/try-gmt/pull/33)
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt/v0-6-0_announcement, requires moderator status) https://forum.generic-mapping-tools.org/t/pygmt-v0-6-0-released/2697
  - [x] [Major/Minor releases only] GMT [website](https://github.com/GenericMappingTools/website) (News) (Now automatic with badges)
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) (after forum announcement) (@meghanrjones)
  - [x] [Twitter](https://twitter.com/gmt_dev) (after forum announcement) https://twitter.com/gmt_dev/status/1503540119315357699
---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by meghanrjones** [comment]
I'll post the changelog draft shortly. I don't have much more time available today, but would be available to help sprint on finishing https://github.com/GenericMappingTools/pygmt/pull/731 tomorrow if we want to try to get that in for this release.

**Comment by meghanrjones** [comment]
Even though https://github.com/GenericMappingTools/pygmt/pull/1812 was opened after the PR due date, I would prefer to include it in this release so that we don't need to worry about backwards compatibility for the ``outgrid`` parameter.

**Comment by weiji14** [comment]
Ok, Zenodo release is up at [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5607255.svg)](https://doi.org/10.5281/zenodo.5607255). The docs look good and PyPI upload seems to be working. Who wants to do the announcements (put your name next to the checklist)!

**Comment by weiji14** [comment]
I'll go ahead and make the forum announcement and Twitter post since it's getting a bit late on my end. If someone else can pick up on the other items, that would be wonderful.

**Comment by meghanrjones** [comment]
Thanks @weiji14! I'll post on research gate after https://github.com/GenericMappingTools/try-gmt/pull/33 is merged. We no longer need to submit PRs for the website for every release since I updated the home page to use badges.

**Comment by meghanrjones** [comment]
All done! Great work and many thanks to the PyGMT team :tada:
