### ISSUE TITLE
List of failing tests for GMT 6.4

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1885]
Following is a long list of 70 failing tests for the upcoming GMT dev version. 

- [x] `../tests/test_basemap.py::test_basemap_polar` (#1886)
- [x] `../tests/test_basemap.py::test_basemap_utm_projection[EPSG_32723 +width=5]` (#1886)
- [x] `../tests/test_basemap.py::test_basemap_utm_projection[+proj=utm +zone=23 +south +datum=WGS84 +units=m +no_defs +width=5]` (#1886)
- [x] `../tests/test_basemap.py::test_basemap_compass` (#1886)
- [x] `../tests/test_config.py::test_config_font_one` (#1901)
- [x] `../tests/test_config.py::test_config_font_annot` (#1901)
- [x] `../tests/test_config.py::test_config_format_date_map` (86b95cf8)
- [x] `../tests/test_contour.py::test_contour_vec` (#1887)
- [x] `../tests/test_contour.py::test_contour_incols_transposed_data` (#1887)
- [x] `../tests/test_dimfilter.py::test_dimfilter_outgrid` (https://github.com/GenericMappingTools/gmt/pull/6619)
- [x] `../tests/test_dimfilter.py::test_dimfilter_no_outgrid` (https://github.com/GenericMappingTools/gmt/pull/6619)
- [x] `../tests/test_geopandas.py::test_geopandas_plot3d_default_cube` (020cfc7f)
- [x] `../tests/test_geopandas.py::test_geopandas_plot3d_non_default_circle` (020cfc7f)
- [x] `../tests/test_grdcontour.py::test_grdcontour` (1ff96239)
- [x] `../tests/test_grdcontour.py::test_grdcontour_labels` (1ff96239)
- [x] `../tests/test_grdimage.py::test_grdimage` (#1902)
- [x] `../tests/test_grdimage.py::test_grdimage_slice` (#1903)
- [x] `../tests/test_grdimage.py::test_grdimage_file` (#1904)
- [x] `../tests/test_grdimage.py::test_grdimage_default_no_shading[None]` (#1903)
- [x] `../tests/test_grdimage.py::test_grdimage_default_no_shading[False]` (#1903)
- [x] `../tests/test_grdimage.py::test_grdimage_over_dateline` (#1905)
- [x] `../tests/test_grdimage.py::test_grdimage_global_subset` (#1906)
- [x] `../tests/test_grdview.py::test_grdview_with_perspective` (662381b5)
- [x] `../tests/test_grdview.py::test_grdview_with_cmap_for_image_plot` (662381b5)
- [x] `../tests/test_grdview.py::test_grdview_on_a_plane_with_colored_frontal_facade` (662381b5)
- [x] `../tests/test_grdview.py::test_grdview_with_perspective_and_zaxis_frame` (662381b5)
- [x] `../tests/test_image.py::test_image` (9aad494b19f1efc196185873ae69911ea567021b)
- [x] `../tests/test_inset.py::test_inset_context_manager` (#1900)
- [x] `../tests/test_legend.py::test_legend_position` (ecb5b0cc)
- [x] `../tests/test_legend.py::test_legend_default_position` (ecb5b0ccb)
- [x] `../tests/test_legend.py::test_legend_entries` (ecb5b0ccb)
- [x] `../tests/test_legend.py::test_legend_specfile` (https://github.com/GenericMappingTools/pygmt/pull/1898)
- [x] `../tests/test_logo.py::test_logo` (407549e9)
- [x] `../tests/test_makecpt.py::test_makecpt_plot_colorbar_scaled_with_series` (f30e1d07)
- [x] `../tests/test_makecpt.py::test_makecpt_truncated_zlow_zhigh` (f30e1d07)
- [x] `../tests/test_makecpt.py::test_makecpt_reverse_color_only` (f30e1d07)
- [x] `../tests/test_makecpt.py::test_makecpt_reverse_color_and_zsign` (f30e1d07)
- [x] `../tests/test_makecpt.py::test_makecpt_continuous` (f30e1d07)
- [x] `../tests/test_makecpt.py::test_makecpt_categorical` (#1899)
- [x] `../tests/test_meca.py::test_meca_spec_dataframe` (59d1b279)
- [x] `../tests/test_meca.py::test_meca_spec_1d_array` (59d1b279)
- [x] `../tests/test_plot.py::test_plot_colors_sizes_proj` (d42ef499)
- [x] `../tests/test_plot.py::test_plot_matrix[#aaaaaa]` (d42ef499)
- [x] `../tests/test_plot.py::test_plot_matrix[170]` (d42ef499)
- [x] `../tests/test_plot.py::test_plot_shapefile` (https://github.com/GenericMappingTools/pygmt/pull/1897)
- [x] `../tests/test_plot3d.py::test_plot3d_red_circles_zscale` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_projection` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_colors_sizes_proj` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_matrix[#aaaaaa]` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_matrix[170]` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_ogrgmt_file_multipoint_default_style[str]` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_ogrgmt_file_multipoint_default_style[Path]` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_plot3d.py::test_plot3d_ogrgmt_file_multipoint_non_default_style` (4a329f260cd5ac4fa5cd66c2bf68afeb18f550f2)
- [x] `../tests/test_rose.py::test_rose_2d_array_single` (44909074)
- [x] `../tests/test_rose.py::test_rose_2d_array_multiple` (44909074)
- [x] `../tests/test_solar.py::test_solar_terminators` (4cfa4fe6)
- [x] `../tests/test_solar.py::test_solar_set_terminator_datetime[terminator_datetime_string]` (4cfa4fe6)
- [x] `../tests/test_solar.py::test_solar_set_terminator_datetime[terminator_datetime1]` (4cfa4fe6)
- [x] `../tests/test_solar.py::test_solar_default_terminator` (4cfa4fe6)
- [x] `../tests/test_text.py::test_text_single_line_of_text` (269e6b7a)
- [x] `../tests/test_text.py::test_text_multiple_lines_of_text` (269e6b7a)
- [x] `../tests/test_text.py::test_text_position`(269e6b7a)
- [x] `../tests/test_text.py::test_text_position_offset_with_line` (269e6b7a)
- [x] `../tests/test_text.py::test_text_fill` (269e6b7a)
- [x] `../tests/test_text.py::test_text_justify_bottom_right_and_top_left` (269e6b7a)
- [x] `../tests/test_velo.py::test_velo_numpy_array_numeric_only` (#1889)
- [x] `../tests/test_velo.py::test_velo_pandas_dataframe` (#1889)
- [x] `../tests/test_wiggle.py::test_wiggle` (#1888)
- [x] `../tests/test_wiggle.py::test_wiggle_deprecate_columns_to_incols` (#1888)

**Comment by michaelgrund** [comment]
Is there still something to do here @seisman?

**Comment by seisman** [comment]
I'm slowly checking the failing tests and pushing the new baseline images to #1883, so all will be done in #1883 unless some failing tests are caused by GMT or PyGMT bugs.

**Comment by seisman** [comment]
FYI, I've updated 46 baseline images in the gmt-6.4 branch (PR #1883), which should fix ~56 failing tests (some tests share the same baseline image). These tests fail due to tiny changes in gridlines or texts, or upstream fixes that improve the layout (e.g., https://github.com/GenericMappingTools/gmt/issues/6163).

The remaining tests show much bigger changes between the old and new baseline images, so we must carefully check if the changes are correct or not. For these tests, I'll open separate PRs instead of directly pushing the baseline images to the gmt-6.4 branch, so that we can discuss it.

**Comment by seisman** [comment]
FYI, all failing baselines images have been updated and merged into the `gmt-6.4` branch (PR #1883). If you look at the scheduled "GMT Dev Test" CI runs (e.g., https://github.com/GenericMappingTools/pygmt/runs/6298988995?check_suite_focus=true), you will see all tests pass except four. The four tests fail because I've updated the test functions in the `gmt-6.4` branch to generate more reasonable baseline images, but the scheduled CI jobs run  "tests in the **main** branch" + "baseline images in the **gmt-6.4** branch" + "GMT dev source code".
