### ISSUE TITLE
Bump to GMT 6.4.0

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1989]
:tada: [GMT 6.4.0](https://github.com/GenericMappingTools/gmt/releases/tag/6.4.0) has been released! It is installable from the
[conda-forge channel](https://anaconda.org/conda-forge/gmt/files) using the following command:

`conda install -c conda-forge gmt=6.4.0`

**To-Do for bumping the GMT version in CI**:

- [x] Bump the GMT version in CI (1 PR) (https://github.com/GenericMappingTools/pygmt/pull/1990)
  - [x] Update `.github/workflows/cache_data.yaml`
  - [x] Update `.github/workflows/ci_docs.yml`
  - [x] Update `.github/workflows/ci_tests.yaml`
  - [x] Update `ci/requirements/docs.yml`
  - [x] Update `environment.yml`
- [ ] Fix failing tests (1 or more PRs) (https://github.com/GenericMappingTools/pygmt/pull/2052)
- [x] Fix [xfail](https://docs.pytest.org/en/stable/skipping.html#xfail-mark-test-functions-as-expected-to-fail) pytest markers on tests that are now xpass
