### ISSUE TITLE
Use ruff to improve code quality

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2741]
It seems [ruff](https://github.com/astral-sh/ruff) has been very hot recently. The README says it can replace flake8 and pylint, and more importantly, it's 10-100x faster.

Someone interested may try it and tell us how it works for the PyGMT project.

**Comment by weiji14** [comment]
Opened a PR to replace `flakeheaven` and `isort` with `ruff` at #2747, so that we can move ahead with the Python 3.12 support.

It should also be possible to replace `pylint` with `ruff` (see https://docs.astral.sh/ruff/faq/#how-does-ruff-compare-to-pylint), which would:
- Pro:
  - Allow us to remove `make lint` (which is slow) from the Makefile (i.e. only have `make check` and `make format`)
  - Bonus is that `ruff` can actually automatically fix some pylint rules (see those marked with 🛠️ at https://docs.astral.sh/ruff/rules/#pylint-pl)
- Con: Not all pylint rules are applied (see https://github.com/astral-sh/ruff/issues/970), but I'm not sure if we even need to check all of them...

So should we replace `pylint` with `ruff`? Vote :+1: for yes, :-1: for no. If everyone is generally in favour, we can open a PR after #2747 is merged.

**Comment by seisman** [comment]
> So should we replace `pylint` with `ruff`?

Instead of replacing `pylint` with `ruff`, I think we can use both to see if there are any linting issues reported by pylint but not detected by `ruff`. We can then decide if we want to remove `pylint` before releasing v0.11.0. So I propose to have two separate PRs:

- [ ] Configure `ruff` as a linting tool
- [ ] Remove `pylint` before v0.11.0

**Comment by seisman** [comment]
**Last updated on 2024/11/29**

ruff supports many groups of rules (https://docs.astral.sh/ruff/rules/). I think we should go through the available rules and apply the rules that make sense to our project.

ruff v0.16.0 (released on 2026/07) provides the following linters/rules:
```
ruff linter | sort -k1 | awk '{printf("- [ ] [`%s`](https://docs.astral.sh/ruff/rules/#%s-%s): %s\n"), $1, tolower($2), tolower($1), $2}' 
```

- [x] [`A`](https://docs.astral.sh/ruff/rules/#flake8-builtins-a): flake8-builtins #2882
- [ ] ~~[`AIR`](https://docs.astral.sh/ruff/rules/#airflow-air): Airflow~~ [unrelated to airflow]
- [ ] [`ANN`](https://docs.astral.sh/ruff/rules/#flake8-annotations-ann): flake8-annotations [This ruleset checks annotations of all parameters. So, we can't enable this ruleset until we're 100% type-complete]
- [x] [`ARG`](https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg): flake8-unused-arguments #2900
- [ ] ~~[`ASYNC`](https://docs.astral.sh/ruff/rules/#flake8-async-async): flake8-async~~  [async is not used in pygmt]
- [x] [`B`](https://docs.astral.sh/ruff/rules/#flake8-bugbear-b): flake8-bugbear #2825
- [x] [`BLE`](https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble): flake8-blind-except #2878
- [x] [`C4`](https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4): flake8-comprehensions #2887
- [ ] [`C90`](https://docs.astral.sh/ruff/rules/#mccabe-c90): mccabe [Some functions have high complexity but it's a lot of work to refactor them]
- [x] [`COM`](https://docs.astral.sh/ruff/rules/#flake8-commas-com): flake8-commas #3531
- [ ] ~~[`CPY`](https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy): flake8-copyright~~ [we don't have copyright in any files]
- [ ] ~~[`DJ`](https://docs.astral.sh/ruff/rules/#flake8-django-dj): flake8-django~~ [not a django project]
- [ ] [`DOC`](https://docs.astral.sh/ruff/rules/#pydoclint-doc): pydoclint [preview only]
- [x] [`D`](https://docs.astral.sh/ruff/rules/#pydocstyle-d): pydocstyle #2925
- [ ] ~~[`DTZ`](https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz): flake8-datetimez~~ [I think we usually don't care about timezones)
- [x] [`EM`](https://docs.astral.sh/ruff/rules/#flake8-errmsg-em): flake8-errmsg #3661
- [ ] ~~[`ERA`](https://docs.astral.sh/ruff/rules/#eradicate-era): eradicate~~ [This linter has one rule to check commented-out Python code. It raises many errors because sometimes we have code-like comments.]
- [x] [`E/W`](https://docs.astral.sh/ruff/rules/#pycodestyle-e/w): pycodestyle #2747
- [x] [`EXE`](https://docs.astral.sh/ruff/rules/#flake8-executable-exe): flake8-executable #2898
- [x] [`FA`](https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa): flake8-future-annotations #2855
- [ ] ~~[`FAST`](https://docs.astral.sh/ruff/rules/#fastapi-fast): FastAPI~~ [unrelated to FastAPI]
- [ ] [`FBT`](https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt): flake8-boolean-trap [This ruleset causes too many errors. Better to refactor the function definition in #2893 first]
- [ ] ~~[`FIX`](https://docs.astral.sh/ruff/rules/#flake8-fixme-fix): flake8-fixme~~ [FIXME is not used in pygmt]
- [x] [`FLY`](https://docs.astral.sh/ruff/rules/#flynt-fly): flynt #2835
- [x] [`F`](https://docs.astral.sh/ruff/rules/#pyflakes-f): Pyflakes #2747
- [x] [`FURB`](https://docs.astral.sh/ruff/rules/#refurb-furb): refurb #3531
- [ ] ~~[`G`](https://docs.astral.sh/ruff/rules/#flake8-logging-format-g): flake8-logging-format~~ [logging is not used in pygmt]
- [x] [`ICN`](https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn): flake8-import-conventions #2878
- [x] [`I`](https://docs.astral.sh/ruff/rules/#isort-i): isort #2747
- [ ] ~~[`INP`](https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp): flake8-no-pep420~~ [report too many errors about examples]
- [ ] ~~[`INT`](https://docs.astral.sh/ruff/rules/#flake8-gettext-int): flake8-gettext~~ [gettext is not used in pygmt]
- [x] [`ISC`](https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc): flake8-implicit-str-concat #2837
- [ ] ~~[`LOG`](https://docs.astral.sh/ruff/rules/#flake8-logging-log): flake8-logging~~ [logging is not used in pygmt]
- [x] [`N`](https://docs.astral.sh/ruff/rules/#pep8-naming-n): pep8-naming #2877
- [x] [`NPY`](https://docs.astral.sh/ruff/rules/#numpy-specific-npy): NumPy-specific #2782
- [x] [`PD`](https://docs.astral.sh/ruff/rules/#pandas-vet-pd): pandas-vet #2830
- [x] [`PERF`](https://docs.astral.sh/ruff/rules/#perflint-perf): Perflint #2886
- [x] [`PGH`](https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh): pygrep-hooks #2878
- [x] [`PIE`](https://docs.astral.sh/ruff/rules/#flake8-pie-pie): flake8-pie #2866
- [x] [`PL`](https://docs.astral.sh/ruff/rules/#pylint-pl): Pylint #2815
- [x] [`PT`](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt): flake8-pytest-style #2899
- [x] [`PTH`](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth): flake8-use-pathlib [too many violations. Address #1834 first]
- [ ] ~~[`PYI`](https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi): flake8-pyi~~ [PyGMT doesn't provide `.pyi` files]
- [ ] ~~[`Q`](https://docs.astral.sh/ruff/rules/#flake8-quotes-q): flake8-quotes~~ [`ruff format` already enforces consistent quote style. The rules are redundant]
- [x] [`RET`](https://docs.astral.sh/ruff/rules/#flake8-return-ret): flake8-return #2897
- [x] [`RSE`](https://docs.astral.sh/ruff/rules/#flake8-raise-rse): flake8-raise #2878
- [x] [`RUF`](https://docs.astral.sh/ruff/rules/#ruff-specific-ruf): Ruff-specific #2901
- [x] [`S`](https://docs.astral.sh/ruff/rules/#flake8-bandit-s): flake8-bandit #2892
- [x] [`SIM`](https://docs.astral.sh/ruff/rules/#flake8-simplify-sim): flake8-simplify #2829
- [ ] ~~[`SLF`](https://docs.astral.sh/ruff/rules/#flake8-self-slf): flake8-self~~ [I believe we only access class private members when necessary]
- [ ] ~~[`SLOT`](https://docs.astral.sh/ruff/rules/#flake8-slots-slot): flake8-slots~~ [pygmt has no subclasses of immutable types]
- [ ] ~~[`T10`](https://docs.astral.sh/ruff/rules/#flake8-debugger-t10): flake8-debugger~~ [no debugger information in pygmt]
- [x] [`T20`](https://docs.astral.sh/ruff/rules/#flake8-print-t20): flake8-print #2894
- [x] [`TC`](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch): flake8-type-checking #2878
- [x] [`TD`](https://docs.astral.sh/ruff/rules/#flake8-todos-td): flake8-todos   #3723
- [x] [`TID`](https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid): flake8-tidy-imports #2878
- [x] [`TRY`](https://docs.astral.sh/ruff/rules/#tryceratops-try): tryceratops #3665
- [x] [`UP`](https://docs.astral.sh/ruff/rules/#pyupgrade-up): pyupgrade #2749
- [x] [`YTT`](https://docs.astral.sh/ruff/rules/#flake8-2020-ytt): flake8-2020 #2878

**Comment by seisman** [comment]
I've enabled ~32 rulesets that make sense to our project. Closing the issue now and we may revisit it in the feature if new ruff versions provide more rulesets.

**Comment by weiji14** [comment]
> * [ ]  [`FURB`](https://docs.astral.sh/ruff/rules/#refurb-furb): refurb [preview only]

I've been trying out some of these `FURB` rules in preview by running [`ruff check . --statistics`](https://astral.sh/blog/ruff-v0.5.0#-statistics-now-shows-rule-names), and got the following output at commit 41a0fe0a6a79849565348203737360855d40add8 (those marked with an asterisk * are automatically fixable):

```
ruff check . --statistics
16	PLR6201	[*] Use a `set` literal when testing for membership
15	PLC0415	[ ] `import` should be at the top-level of a file
15	PLW1514	[*] `pathlib.Path(...).open` in text mode without explicit `encoding` argument
 8	E226   	[*] Missing whitespace around arithmetic operator
 4	S404   	[ ] `subprocess` module is possibly insecure
 3	PLR6104	[*] Use `+=` to perform an augmented assignment directly
 3	FURB113	[*] Use `lines.extend(('WARNING:', f'  {warnmsg}'))` instead of repeatedly calling `lines.append()`
 2	PLC1901	[ ] `err == ""` can be simplified to `not err` as an empty string is falsey
 2	PLW3201	[ ] Bad or misspelled dunder method name `_repr_html_`
 1	PLR0904	[ ] Too many public methods (30 > 20)
 1	PLR0917	[ ] Too many positional arguments (11/10)
 1	PLW0108	[*] Lambda may be unnecessary; consider inlining inner function
 1	RUF027 	[*] Possible f-string without an `f` prefix
```

**Comment by seisman** [comment]
Sounds good.
