### ISSUE TITLE
Release PyGMT v0.11.0

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2843]
**Release**: [v0.11.0](https://github.com/GenericMappingTools/pygmt/milestones/17)
**Scheduled Date**: 2024/02/01
**Pull request due date**: 2024/01/29

**Priority PRs/issues to complete prior to release**

- [x] Planetary relief datasets from https://github.com/GenericMappingTools/pygmt/issues/2431
- [x] Bump to GMT 6.5.0 #2961
- [x] Bump Ghostscript to 10.02.1 #2694
- [x] Update baseline images to match GMT 6.5.0 + Ghostscript 10.02.1 #2961

**Before release**:
- [x] Check [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) to see if we need to bump the minimum Python and NumPy versions
- [x] Run `make codespell` to check common misspellings. If there are any, either fix them or add them to `ignore-words-list` in `pyproject.toml`
- [x] Check to ensure that:
  - [x] All tests pass in the ["GMT Legacy Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_legacy.yaml) #3021
  - [x] All tests pass in the ["GMT Dev Tests" workflow](https://github.com/GenericMappingTools/pygmt/actions/workflows/ci_tests_dev.yaml) (https://github.com/GenericMappingTools/pygmt/issues/2843#issuecomment-1913045122)
  - [x] Deprecations and related tests are removed for this version by running `grep --include="*.py" -r 'remove_version="vX.Y.Z"' pygmt` from the base of the repository
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" `10.5281/zenodo.10578540`
- [x] Finish up 'Changelog entry for v0.x.x' Pull Request: #3022
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update `CITATION.cff` and BibTeX at https://github.com/GenericMappingTools/pygmt#citing-pygmt
    - [x] Update authorship list
    - [x] Update DOI (and url for BibTeX)
    - [x] Update version
    - [x] Update date released
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-gmtpythonnumpy-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice ([see maintainers guide for details](https://www.pygmt.org/dev/maintenance.html#updating-the-changelog))

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Done automatically by conda-forge's bot, but remember to pin NEP29 versions] https://github.com/conda-forge/pygmt-feedstock/pull/29
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (after conda-forge update) https://github.com/GenericMappingTools/try-gmt/commit/53b4e7dc144e4cd2a8bb15d1d8bb245210e35d8d
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw
  - [x] [ResearchGate](https://www.researchgate.net) (after forum announcement, add new version as research item via the **code** category, be sure to include the corresponding new Zenodo DOI) https://www.researchgate.net/publication/377939031_PyGMT_A_Python_interface_for_the_Generic_Mapping_Tools_v0110
---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
Are we planning on releasing this after GMT 6.5.0 - https://github.com/GenericMappingTools/gmt/issues/8017?

**Comment by seisman** [comment]
Hi @GenericMappingTools/pygmt-maintainers, we need to decide the most suitable release date for PyGMT v0.11.0:

- GMT 6.5.0 is planned to be released in a few days (https://github.com/GenericMappingTools/gmt/issues/8017)
- 11-15 Dec is the AGU meeting week
- 25 Dec is the Christmas holiday
- 1 Jan 2024 is the New Year holiday

We will wait for the GMT 6.5.0 release, then the best dates may be 16-24 Dec and 26-31 Dec?

**Comment by yvonnefroehlich** [comment]
> Hi @GenericMappingTools/pygmt-maintainers, we need to decide the most suitable release date for PyGMT v0.11.0:
> 
> * GMT 6.5.0 is planned to be released in a few days ([Release GMT 6.5.0 gmt#8017](https://github.com/GenericMappingTools/gmt/issues/8017))
> * 11-15 Dec is the AGU meeting week

For me AGU is not relevant.

> * 25 Dec is the Christmas holiday

At least in Germany 25 Dec and 26 Dec are both public Christmas holidays :laughing:.

> * 1 Jan 2024 is the New Year holiday

Upon 29 or 30 Dec I am probably not available for a few days.

> 
> We will wait for the GMT 6.5.0 release, then the best dates may be 16-24 Dec and 26-31 Dec?

Not sure how realistic it is that people have time to finish and review PRs in the week before Christmas :sweat_smile:.

**Comment by weiji14** [comment]
[GMT 6.5.0 release](https://github.com/GenericMappingTools/gmt/issues/8017) should be close :crossed_fingers:, shall we set a new schedule date for PyGMT v0.11.0? I'm back to work next week, and away for a conference around 18-21 Jan, but could help for a release around end of Jan 2024?

**Comment by Esteban82** [comment]
I think that the pygmt releases should also be announced on instagram. I could do it.

**Comment by seisman** [comment]
Ping @GenericMappingTools/pygmt-maintainers I think it's time to prepare for the v0.11.0 release, which was planned to be released on Jan, 1, 2024 and haven't been postponed due to the GMT 6.5.0 release. Now the new target release date is Feb 1, 2024. Helps are welcomed.

**Comment by seisman** [comment]
There are 4 failures in the "GMT Dev workflow" (see https://github.com/GenericMappingTools/pygmt/actions/runs/7676761841/job/20924687559?pr=3019). The 4 failures are because OpenMP support is not enabled for the GMT dev builds. I've tried to enable openmp support in https://github.com/GenericMappingTools/pygmt/pull/3011, but it turns out more difficult than I initially expected. So, let's address the OpenMP support issue after v0.11.0 release.

**Comment by seisman** [comment]
I've created an initial release announcement (with contents copied from v0.10.0) at https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw.

**Comment by yvonnefroehlich** [comment]
> I've created an initial release announcement (with contents copied from v0.10.0) at https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw.

Thanks @seisman for pushing this forward. I started to adjust the content for v0.11.0.

**Comment by yvonnefroehlich** [comment]
> - [ ] https://github.com/GenericMappingTools/pygmt/issues/2431

We are not planning to add all remote datasets listed at https://github.com/GenericMappingTools/pygmt/issues/2431#issue-1626749146 for v0.11.0, or? If we focus on the planetary reliefs, only Mercury and Pluto are missing.

**Comment by seisman** [comment]
> [ ] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

@weiji14 Need your help here.

**Comment by seisman** [comment]
> * [ ]  GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw

Thanks @yvonnefroehlich for drafting the announcement. It looks good to me.

**Comment by weiji14** [comment]
> > [ ] Manually upload the pygmt-vX.Y.Z.zip and baseline-images.zip files to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI
> 
> @weiji14 Need your help here.

Ok, done at https://doi.org/10.5281/zenodo.10578540!

**Comment by yvonnefroehlich** [comment]
> > * [ ]   GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw
> 
> Thanks @yvonnefroehlich for drafting the announcement. It looks good to me.

So, I can do the forum announcement if everybody else is happy with the draft. Or does somebody else want to do it?

**Comment by weiji14** [comment]
> > > * [ ]   GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw
> > 
> > Thanks @yvonnefroehlich for drafting the announcement. It looks good to me.
> 
> So, I can do the forum announcement if everybody else is happy with the draft. Or does somebody else want to do it?

Sure, go ahead! I just changed some links from `/dev` to `/v0.11.0`, and a couple of typos, and it looks good to me now.

@michaelgrund, do you want to do the ResearchGate post/announcement afterwards?

**Comment by yvonnefroehlich** [comment]
> > > > * [ ]    GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw
> > > 
> > > 
> > > Thanks @yvonnefroehlich for drafting the announcement. It looks good to me.
> > 
> > 
> > So, I can do the forum announcement if everybody else is happy with the draft. Or does somebody else want to do it?
> 
> Sure, go ahead! I just changed some links from `/dev` to `/v0.11.0`, and a couple of typos, and it looks good to me now.
> 

Thanks @weiji14 for adjusting the links. I have posted the announcement on the GMT forum, please see https://forum.generic-mapping-tools.org/t/pygmt-v0-11-0-released/4667.

**Comment by michaelgrund** [comment]
> > > > * [ ]    GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (do this announcement first! draft on https://hackmd.io/@pygmt. requires moderator status) https://hackmd.io/UPCHs1S7SyCmnzvgcRKOUw
> > > 
> > > 
> > > Thanks @yvonnefroehlich for drafting the announcement. It looks good to me.
> > 
> > 
> > So, I can do the forum announcement if everybody else is happy with the draft. Or does somebody else want to do it?
> 
> Sure, go ahead! I just changed some links from `/dev` to `/v0.11.0`, and a couple of typos, and it looks good to me now.
> 
> @michaelgrund, do you want to do the ResearchGate post/announcement afterwards?

Sure, will make the post in RG later :wink: .

**Comment by seisman** [comment]
Thanks everybody for the efforts and help with this release 🎉!
