### ISSUE TITLE
Bump to GMT 6.5.0

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2961]
:tada: [GMT 6.5.0](https://github.com/GenericMappingTools/gmt/releases/tag/6.5.0) has been released! It is installable from the [conda-forge channel](https://anaconda.org/conda-forge/gmt/files) using the following command:

`mamba install -c conda-forge gmt=6.5.0`

**To-Do for bumping the GMT version in CI**:

- [x] Bump the GMT version in CI (1 PR) #2962
  - [x] Update `environment.yml`
  - [x] Update `ci/requirements/docs.yml`
  - [x] Update `.github/workflows/benchmarks.yml`
  - [x] Update `.github/workflows/cache_data.yaml`
  - [x] Update `.github/workflows/ci_doctests.yaml`
  - [x] Update `.github/workflows/ci_docs.yml`
  - [x] Update `.github/workflows/ci_tests.yaml`
  - [x] Add the legacy GMT version to `.github/workflows/ci_tests_legacy.yaml`
  - [x] Update GMT 6.x minor version for `extlinks` urls in `doc/conf.py`
  - [x] Update GMT 6.x minor version in `.github/workflows/check-links.yml`
- [x] Fix failing tests (1 or more PRs)
- [x] Fix [xfail](https://docs.pytest.org/en/stable/skipping.html#xfail-mark-test-functions-as-expected-to-fail) pytest markers on tests that are now xpass
- [x] Fix links to GMT documentation (renaming "cookbook" to "reference"): #2990

**Comment by seisman** [comment]
Probably need to see if there is GMT 6.5.1 (https://github.com/GenericMappingTools/gmt/issues/8265).

**Comment by seisman** [comment]
Since there are ~200 failures, I think it makes more sense to update baseline images by modules.

**Comment by weiji14** [comment]
> Since there are ~200 failures, I think it makes more sense to update baseline images by modules.

Maybe group some of them, otherwise there will be 35 PRs. This is the summary count:

Test | Count | PR
--|--|--
../pygmt/tests/test_basemap.py                                     | 10 |
../pygmt/tests/test_coast.py                                       |  4 |
../pygmt/tests/test_colorbar.py                                    |  6 |
../pygmt/tests/test_config.py                                      | 10 |
../pygmt/tests/test_contour.py                                     |  6 |
../pygmt/tests/test_datasets_earth_age.py                          |  2 |
../pygmt/tests/test_datasets_earth_free_air_anomaly.py             |  2 |
../pygmt/tests/test_datasets_earth_geoid.py                        |  2 |
../pygmt/tests/test_datasets_earth_magnetic_anomaly.py             |  6 |
../pygmt/tests/test_datasets_earth_relief.py                       | 10 |
../pygmt/tests/test_datasets_earth_vertical_gravity_gradient.py    |  2 |
../pygmt/tests/test_geopandas.py                                   |  9 |
../pygmt/tests/test_grd2cpt.py                                     |  1 |
../pygmt/tests/test_grdcontour.py                                  |  4 |
../pygmt/tests/test_grdimage.py                                    |  6 |
../pygmt/tests/test_grdimage_image.py                              |  1 |
../pygmt/tests/test_grdview.py                                     |  1 |
../pygmt/tests/test_helpers.py                                     |  1 |
../pygmt/tests/test_histogram.py                                   |  2 |
../pygmt/tests/test_inset.py                                       |  2 |
../pygmt/tests/test_legend.py                                      |  3 |
../pygmt/tests/test_logo.py                                        |  2 |
../pygmt/tests/test_makecpt.py                                     |  8 |
../pygmt/tests/test_meca.py                                        | 16 |
../pygmt/tests/test_plot.py                                        | 22 |
../pygmt/tests/test_plot3d.py                                      | 13 |
../pygmt/tests/test_rose.py                                        |  7 |
../pygmt/tests/test_subplot.py                                     |  5 |
../pygmt/tests/test_ternary.py                                     |  3 |
../pygmt/tests/test_text.py                                        | 24 |
../pygmt/tests/test_tilemap.py                                     |  4 |
../pygmt/tests/test_timestamp.py                                   |  8 |
../pygmt/tests/test_velo.py                                        |  1 |
../pygmt/tests/test_wiggle.py                                      |  2 |
../pygmt/tests/test_x2sys_cross.py                                 |  3 |

**Comment by seisman** [comment]
Yes, better to have < 10 baseline image changes to make PR review easier.

**Comment by seisman** [comment]
Just in case it may be helpful. Here are the steps I'm using to update baseline images:

1. Check a single test file `pytest pygmt/tests/test_makecpt.py`
2. Go to the `results` directory and visually check the `baseline.png`, `result.png` and `difference.png` (if any)
3. If all `result.png` are correct, run the following command to batch copy the `result.png` to  the `pygmt/tests/baseline` directory:
```
```

**Comment by seisman** [comment]
After PR #2971, #2972 and #2977, we're almost done with updating the baseline images, with a few exceptions.

### colorbars

Here is an example of the old and new baseline images for the `test_colorbar_box` test. As you can see, the colorbar annotations are too small in the new baseline image, which makes me think it's an upstream bug. However, it's just because the colorbar is set to 1 cm long but 0.5 cm high, which I bet no one will use in their papers. So I think we should take the opportunity to  think about how we should test colorbar. Since the `colorbar` wrapper is just a simple wrapper with three lines, maybe we should just keep the simplest test and remove the others?

| old | new |
|---|---|
|![baseline](https://github.com/GenericMappingTools/pygmt/assets/3974108/817afd53-fdc9-4084-8e6b-7f8b7665f73c)|![result](https://github.com/GenericMappingTools/pygmt/assets/3974108/0e8961f0-6b74-4182-aa20-34cdf51bd64c)|

### grdimage

The grdimage failures are most likely caused by the recent updates of the earth relief dataset. I think we should take the opportunity to use the **static** earth relief dataset so that future dataset updates won't cause PyGMT failures.

**Comment by seisman** [comment]
> ### grdimage
> The grdimage failures are most likely caused by the recent updates of the earth relief dataset. I think we should take the opportunity to use the **static** earth relief dataset so that future dataset updates won't cause PyGMT failures.

Unfortunately we can't, because `@static_earth_relief.nc` is not a global grid.

**Comment by michaelgrund** [comment]
The x2sys_cross failures need also to be fixed, right @seisman ?

**Comment by seisman** [comment]
> The x2sys_cross failures need also to be fixed, right @seisman ?

Yes, but I've never used them, so I'm unsure if the new results are correct.

**Comment by weiji14** [comment]
> > The x2sys_cross failures need also to be fixed, right @seisman ?
> 
> Yes, but I've never used them, so I'm unsure if the new results are correct.

Let me look into that. A quick look at the changes in GMT 6.5.0 only showed the addition of a nearest neighbour interpolation method to `x2sys_cross` in https://github.com/GenericMappingTools/gmt/pull/7984, but that shouldn't have affected the results from the default linear interpolation method.

**Comment by seisman** [comment]
Some doctests also fail but are skipped in the "Tests" workflow.

```
$ export PYGMT_USE_EXTERNAL_DISPLAY=false && pytest pygmt/src/**.py

========================================== short test summary info ==========================================
FAILED pygmt/src/grd2xyz.py::pygmt.src.grd2xyz.grd2xyz
FAILED pygmt/src/grdclip.py::pygmt.src.grdclip.grdclip
FAILED pygmt/src/grdhisteq.py::pygmt.src.grdhisteq.grdhisteq.compute_bins
FAILED pygmt/src/grdproject.py::pygmt.src.grdproject.grdproject
FAILED pygmt/src/grdvolume.py::pygmt.src.grdvolume.grdvolume
FAILED pygmt/src/grd2xyz.py::pygmt.src.grd2xyz.grd2xyz
FAILED pygmt/src/grdclip.py::pygmt.src.grdclip.grdclip
FAILED pygmt/src/grdhisteq.py::pygmt.src.grdhisteq.grdhisteq.compute_bins
FAILED pygmt/src/grdproject.py::pygmt.src.grdproject.grdproject
FAILED pygmt/src/grdvolume.py::pygmt.src.grdvolume.grdvolume
```

<details>

```
================================================= FAILURES ==================================================
____________________________________ [doctest] pygmt.src.grd2xyz.grd2xyz ____________________________________
250 -------
251 >>> import pygmt
252 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
253 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
254 >>> grid = pygmt.datasets.load_earth_relief(
255 ...     resolution="30m", region=[10, 30, 15, 25]
256 ... )
257 >>> # Create a pandas DataFrame with the xyz data from an input grid
258 >>> xyz_dataframe = pygmt.grd2xyz(grid=grid, output_type="pandas")
259 >>> xyz_dataframe.head(n=2)
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
         lon   lat  elevation
    -0  10.0  25.0      863.0
    -1  10.5  25.0      985.5
    +0  10.0  25.0      965.5
    +1  10.5  25.0      876.5

/home/seisman/OSS/gmt/pygmt/pygmt/src/grd2xyz.py:259: DocTestFailure
____________________________________ [doctest] pygmt.src.grdclip.grdclip ____________________________________
108 Example
109 -------
110 >>> import pygmt
111 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
112 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
113 >>> grid = pygmt.datasets.load_earth_relief(
114 ...     resolution="30m", region=[10, 30, 15, 25]
115 ... )
116 >>> # Report the minimum and maximum data values
117 >>> [grid.data.min(), grid.data.max()]
Expected:
    [170.0, 2275.5]
Got:
    [183.5, 1807.0]

/home/seisman/OSS/gmt/pygmt/pygmt/src/grdclip.py:117: DocTestFailure
___________________________ [doctest] pygmt.src.grdhisteq.grdhisteq.compute_bins ____________________________
327 >>> import pygmt
328 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
329 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
330 >>> grid = pygmt.datasets.load_earth_relief(
331 ...     resolution="30m", region=[10, 30, 15, 25]
332 ... )
333 >>> # Find elevation intervals that split the data range into 5
334 >>> # divisions, each of which have an equal area in the original grid.
335 >>> bins = pygmt.grdhisteq.compute_bins(grid=grid, divisions=5)
336 >>> print(bins)
Differences (unified diff with -expected +actual):
    @@ -1,7 +1,7 @@
             start    stop
    -bin_id
    -0       170.0   389.0
    -1       389.0   470.5
    -2       470.5   571.0
    -3       571.0   705.0
    -4       705.0  2275.5
    +bin_id               
    +0       183.5   395.0
    +1       395.0   472.0
    +2       472.0   575.0
    +3       575.0   709.5
    +4       709.5  1807.0

/home/seisman/OSS/gmt/pygmt/pygmt/src/grdhisteq.py:336: DocTestFailure
_________________________________ [doctest] pygmt.src.grdproject.grdproject _________________________________
179 >>> import pygmt
180 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
181 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
182 >>> grid = pygmt.datasets.load_earth_relief(
183 ...     resolution="30m", region=[10, 30, 15, 25]
184 ... )
185 >>> # Create a new grid from the input grid, set the projection to
186 >>> # Mercator, and set inverse to "True" to change from "geographic"
187 >>> # to "rectangular"
188 >>> new_grid = pygmt.grdproject(grid=grid, projection="M10c", inverse=True)
UNEXPECTED EXCEPTION: GMTCLibError("Module 'grdproject' failed with status code 72:\ngrdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R")
Traceback (most recent call last):
  File "/home/seisman/opt/miniconda/envs/pygmt/lib/python3.12/doctest.py", line 1357, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest pygmt.src.grdproject.grdproject[2]>", line 1, in <module>
  File "/home/seisman/OSS/gmt/pygmt/pygmt/helpers/decorators.py", line 603, in new_module
    return module_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seisman/OSS/gmt/pygmt/pygmt/helpers/decorators.py", line 776, in new_module
    return module_func(*bound.args, **bound.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seisman/OSS/gmt/pygmt/pygmt/src/grdproject.py", line 122, in grdproject
    lib.call_module(
  File "/home/seisman/OSS/gmt/pygmt/pygmt/clib/session.py", line 624, in call_module
    raise GMTCLibError(
pygmt.exceptions.GMTCLibError: Module 'grdproject' failed with status code 72:
grdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R
/home/seisman/OSS/gmt/pygmt/pygmt/src/grdproject.py:188: UnexpectedException
------------------------------------------- Captured stderr call --------------------------------------------
grdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R
__________________________________ [doctest] pygmt.src.grdvolume.grdvolume __________________________________
108 ...     resolution="30m", region=[10, 30, 15, 25]
109 ... )
110 >>> # Create a pandas dataframe that contains the contour, area, volume,
111 >>> # and maximum mean height above the plane specified by the given
112 >>> # contour and below the surface; set the minimum contour z-value to
113 >>> # 200, the maximum to 400, and the interval to 50.
114 >>> output_dataframe = pygmt.grdvolume(
115 ...     grid=grid, contour=[200, 400, 50], output_type="pandas"
116 ... )
117 >>> print(output_dataframe)
Differences (unified diff with -expected +actual):
    @@ -1,6 +1,6 @@
    -    0             1             2           3
    -0  200  2.318187e+12  8.533727e+14  368.120722
    -1  250  2.272471e+12  7.383936e+14  324.929840
    -2  300  2.162074e+12  6.273066e+14  290.141086
    -3  350  2.018302e+12  5.222640e+14  258.764032
    -4  400  1.857370e+12  4.252699e+14  228.963499
    +     0             1             2           3
    +0  200  2.323600e+12  8.523815e+14  366.836554
    +1  250  2.275864e+12  7.371655e+14  323.905736
    +2  300  2.166707e+12  6.258570e+14  288.851699
    +3  350  2.019284e+12  5.207732e+14  257.899955
    +4  400  1.870441e+12  4.236191e+14  226.480847

/home/seisman/OSS/gmt/pygmt/pygmt/src/grdvolume.py:117: DocTestFailure
____________________________________ [doctest] pygmt.src.grd2xyz.grd2xyz ____________________________________
250 -------
251 >>> import pygmt
252 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
253 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
254 >>> grid = pygmt.datasets.load_earth_relief(
255 ...     resolution="30m", region=[10, 30, 15, 25]
256 ... )
257 >>> # Create a pandas DataFrame with the xyz data from an input grid
258 >>> xyz_dataframe = pygmt.grd2xyz(grid=grid, output_type="pandas")
259 >>> xyz_dataframe.head(n=2)
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
         lon   lat  elevation
    -0  10.0  25.0      863.0
    -1  10.5  25.0      985.5
    +0  10.0  25.0      965.5
    +1  10.5  25.0      876.5

/home/seisman/OSS/gmt/pygmt/pygmt/src/grd2xyz.py:259: DocTestFailure
____________________________________ [doctest] pygmt.src.grdclip.grdclip ____________________________________
108 Example
109 -------
110 >>> import pygmt
111 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
112 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
113 >>> grid = pygmt.datasets.load_earth_relief(
114 ...     resolution="30m", region=[10, 30, 15, 25]
115 ... )
116 >>> # Report the minimum and maximum data values
117 >>> [grid.data.min(), grid.data.max()]
Expected:
    [170.0, 2275.5]
Got:
    [183.5, 1807.0]

/home/seisman/OSS/gmt/pygmt/pygmt/src/grdclip.py:117: DocTestFailure
___________________________ [doctest] pygmt.src.grdhisteq.grdhisteq.compute_bins ____________________________
327 >>> import pygmt
328 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
329 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
330 >>> grid = pygmt.datasets.load_earth_relief(
331 ...     resolution="30m", region=[10, 30, 15, 25]
332 ... )
333 >>> # Find elevation intervals that split the data range into 5
334 >>> # divisions, each of which have an equal area in the original grid.
335 >>> bins = pygmt.grdhisteq.compute_bins(grid=grid, divisions=5)
336 >>> print(bins)
Differences (unified diff with -expected +actual):
    @@ -1,7 +1,7 @@
             start    stop
    -bin_id
    -0       170.0   389.0
    -1       389.0   470.5
    -2       470.5   571.0
    -3       571.0   705.0
    -4       705.0  2275.5
    +bin_id               
    +0       183.5   395.0
    +1       395.0   472.0
    +2       472.0   575.0
    +3       575.0   709.5
    +4       709.5  1807.0

/home/seisman/OSS/gmt/pygmt/pygmt/src/grdhisteq.py:336: DocTestFailure
_________________________________ [doctest] pygmt.src.grdproject.grdproject _________________________________
179 >>> import pygmt
180 >>> # Load a grid of @earth_relief_30m data, with a longitude range of
181 >>> # 10° E to 30° E, and a latitude range of 15° N to 25° N
182 >>> grid = pygmt.datasets.load_earth_relief(
183 ...     resolution="30m", region=[10, 30, 15, 25]
184 ... )
185 >>> # Create a new grid from the input grid, set the projection to
186 >>> # Mercator, and set inverse to "True" to change from "geographic"
187 >>> # to "rectangular"
188 >>> new_grid = pygmt.grdproject(grid=grid, projection="M10c", inverse=True)
UNEXPECTED EXCEPTION: GMTCLibError("Module 'grdproject' failed with status code 72:\ngrdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R")
Traceback (most recent call last):
  File "/home/seisman/opt/miniconda/envs/pygmt/lib/python3.12/doctest.py", line 1357, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest pygmt.src.grdproject.grdproject[2]>", line 1, in <module>
  File "/home/seisman/OSS/gmt/pygmt/pygmt/helpers/decorators.py", line 603, in new_module
    return module_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seisman/OSS/gmt/pygmt/pygmt/helpers/decorators.py", line 776, in new_module
    return module_func(*bound.args, **bound.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seisman/OSS/gmt/pygmt/pygmt/src/grdproject.py", line 122, in grdproject
    lib.call_module(
  File "/home/seisman/OSS/gmt/pygmt/pygmt/clib/session.py", line 624, in call_module
    raise GMTCLibError(
pygmt.exceptions.GMTCLibError: Module 'grdproject' failed with status code 72:
grdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R
/home/seisman/OSS/gmt/pygmt/pygmt/src/grdproject.py:188: UnexpectedException
------------------------------------------- Captured stderr call --------------------------------------------
grdproject [ERROR]: Option -J: If map width is given you must also specify a region with -R
__________________________________ [doctest] pygmt.src.grdvolume.grdvolume __________________________________
108 ...     resolution="30m", region=[10, 30, 15, 25]
109 ... )
110 >>> # Create a pandas dataframe that contains the contour, area, volume,
111 >>> # and maximum mean height above the plane specified by the given
112 >>> # contour and below the surface; set the minimum contour z-value to
113 >>> # 200, the maximum to 400, and the interval to 50.
114 >>> output_dataframe = pygmt.grdvolume(
115 ...     grid=grid, contour=[200, 400, 50], output_type="pandas"
116 ... )
117 >>> print(output_dataframe)
Differences (unified diff with -expected +actual):
    @@ -1,6 +1,6 @@
    -    0             1             2           3
    -0  200  2.318187e+12  8.533727e+14  368.120722
    -1  250  2.272471e+12  7.383936e+14  324.929840
    -2  300  2.162074e+12  6.273066e+14  290.141086
    -3  350  2.018302e+12  5.222640e+14  258.764032
    -4  400  1.857370e+12  4.252699e+14  228.963499
    +     0             1             2           3
    +0  200  2.323600e+12  8.523815e+14  366.836554
    +1  250  2.275864e+12  7.371655e+14  323.905736
    +2  300  2.166707e+12  6.258570e+14  288.851699
    +3  350  2.019284e+12  5.207732e+14  257.899955
    +4  400  1.870441e+12  4.236191e+14  226.480847
```

</details>

We decided to skip some inline doctests to avoid slowing our tests in PR #1790, but these tests may be outdated and failures may be uncaught. We should:

- Fix these failing inline doctests
- Run the full tests when a PR is merged into the main branch or in a scheduled job
