### ISSUE TITLE
Remove the deprecated parameter and alias names in v0.12.0

### ISSUE THREAD

**Issue by michaelgrund** [GenericMappingTools/pygmt#3033]
Several parameters and a few aliases are deprecated since v0.8.0, v0.9.0 or v0.10.0 and the deprecation warnings need to be removed before release v0.12.0.

This issue is created to track the progress of removing these deprecation warnings:

- [x] All plotting methods: Remove aliases `xshift (X)` and `yshift (Y)` (FutureWarning raised since PyGMT v0.8.0) https://github.com/GenericMappingTools/pygmt/pull/3044
- [x] All plotting methods: Remove alias `timestamp (U)` (FutureWarning raised since PyGMT v0.9.0) https://github.com/GenericMappingTools/pygmt/pull/3045
- [x]  `Figure.plot`, `Figure.plot3d`, `Figure.rose`: Remove parameter `color`, use `fill` instead (FutureWarning raised since PyGMT v0.8.0) #3032 
- [x]    `Figure.velo`:  #3034 
   - Remove parameter `uncertaintycolor`, use `uncertaintyfill` instead (FutureWarning raised since PyGMT v0.8.0) 
   - Remove parameter `color`, use `fill` instead
- [x]    `Figure.wiggle`: Remove parameter `color`, use `fillnegative` or `fillpositive` instead (FutureWarning raised since PyGMT v0.8.0) #3035
- [x]    `Figure.grdimage`: Remove parameter `bit_color`, use `bitcolor` instead (Future Warning raised since PyGMT v0.10.0) #3036

**Comment by weiji14** [comment]
Thanks @michaelgrund for keeping track! Ok to open the PRs, but let's wait for a week or two (around mid-Feb) before merging, in case there's some serious bug with PyGMT v0.11.0 and we need to release v0.11.1 to patch it.

**Comment by michaelgrund** [comment]
Sure @weiji14 , definitely fine for me.

**Comment by seisman** [comment]
> let's wait for a week or two (around mid-Feb) before merging, in case there's some serious bug with PyGMT v0.11.0 and we need to release v0.11.1 to patch it.

We don't have to wait. We can always create a patch release from the v0.11.0 tag if there are any serious bugs.

**Comment by weiji14** [comment]
> We don't have to wait. We can always create a patch release from the v0.11.0 tag if there are any serious bugs.

Sure, we can do that, just slightly more work since we need a commit on the main branch, and a backport commit on a patch branch going off from v0.11.0.
