### ISSUE TITLE
Use "TODO" comments to track deprecated codes or workarounds for old versions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3705]
Sometimes, we may need to mark part of the codes for future reference. For example,

1. Deprecated parameters/syntax/functions/methods should be removed in the future. E.g., https://github.com/GenericMappingTools/pygmt/blob/5702209b58443b60e05bc59c233e961e03302bde/pygmt/clib/session.py#L1940-L1944
2. Workarounds for old package versions should be removed after we drop the support of old versions. E.g.,
https://github.com/GenericMappingTools/pygmt/blob/5702209b58443b60e05bc59c233e961e03302bde/pygmt/clib/conversion.py#L180-L187
https://github.com/GenericMappingTools/pygmt/blob/5702209b58443b60e05bc59c233e961e03302bde/pygmt/src/timestamp.py#L102
https://github.com/GenericMappingTools/pygmt/blob/5702209b58443b60e05bc59c233e961e03302bde/pygmt/conftest.py#L8-L9 
3. More other cases.

Currently, for case 1, we use the `grep --include="*.py" -r vX.Y.Z` command to find the matches, but for case 2, we don't have a way to track them.

To better track codes that should be removed/refactored in the future, I suggest using the TODO comments in our source codes. It should be noted that TODO comments should not be abused for marking unimplemented features or incomplete documentation, which should be tracked by issues instead. 

There is no style guide like PEP8 for TODO comments. Looking at this todo tool (https://github.com/ianlewis/todos), the [ruff's TODO linter,](https://docs.astral.sh/ruff/rules/#flake8-todos-td) and also searching for the web, here are the TODO comment styles I've found:

```
# TODO: Description 
# TODO(somebody): Description
# TODO@somebody: Description
# TODO(#1234567): Description
``` 
Since we're using TODO comments for tracking deprecated codes/workarounds, I think we can use the following style:
```
# TODO(Package>=vX.Y.Z): Description
```
e.g., 
```
# TODO(GMT>=6.5.0): Remove the workaround below.
# TOOD(pandas>=2.0): Remove the workaround for pandas<2.0.
# TODO(PyGMT>=0.16.0): Remove the deprecated parameter/function/method ...
```

Then we can use `grep "# TODO" **/*` to find all TODOs. Some editors even have plugins to highlight TODO comments or show all TODOs in a compact way.

If agreed, we should do:

- [x] Find all TODOs in our codebase and refactor them into TODO comments #3722
- [x] Enable some rules in ruff's [TD](https://docs.astral.sh/ruff/rules/#flake8-todos-td) linter #3723
- [x] Mention TODO comments in the contributing guides #3724 
- [x] Update our release checklist #3724
