### ISSUE TITLE
Release PyGMT 0.2.0

### ISSUE THREAD

**Issue by weiji14** [GenericMappingTools/pygmt#587]
**Release**: [v0.2.0](https://github.com/GenericMappingTools/pygmt/milestones/0.2.0)
**Scheduled Date**: 2020/09/12

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version"
- [x] Update Changelog (#599)

**Release**:
- ~~Make a tag and push it to Github~~
- [x] Go to [GitHub Release](https://github.com/GenericMappingTools/pygmt/releases) and make a release, this will automatically create a tag too.
- [x] Manually upload the pygmt-vX.Y.Z.zip file to https://zenodo.org/deposit, make sure you file it under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot] https://github.com/conda-forge/pygmt-feedstock/pull/8
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt
- [ ] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (https://forum.generic-mapping-tools.org/t/pygmt-v0-2-0-released/879)
  - [ ] GMT [website](https://github.com/GenericMappingTools/website) (News) https://github.com/GenericMappingTools/website/pull/69
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) ([link](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools/update/5f5d40c97600090001e6ed7c))
- ~~Create branch 0.x for bug-fixes if this is a minor release (i.e. create branch 0.1 after 0.1.0 is released)~~
- ~~Commit changes to Github~~
---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
Scheduling this release tentatively for Thursday 10 Sep 2020 (UTC time), since Tuesday is a public holiday in the US. Below is a list of outstanding PRs, **please** let us know if there's anything that should be prioritized for the next few days (e.g. it would help with your research/day-job), and we can try to re-arrange some things (on a best effort basis).

Essential bugfix :beetle: PRs for this release, which we should try our best to do:
- [ ] #522 Update 6 baseline images due to GMT 6.1.0 changes (if not too much work)
- [ ] #560 Ensure plotting xarray grids with different central meridians work, though we won't resolve #390 properly yet
- [ ] #581 Add a test for xarray shading

Nice to have enhancements :sparkles:, can wait for next patch release (v0.2.1), or get into v0.2.0 if someone reviews and approves them :smile::
- [ ] #480 Add tutorial for pygmt.Figure.text
- [ ] #482 Tutorial covering pygmt.config
- [ ] #559 Refactor text to use virtualfile_from_vectors instead of pandas tempfile
- [ ] #574 Allow pandas.DataFrame table inputs into pygmt.info
- [ ] #575 Sensible array outputs for pygmt info
- [ ] #576 Allow for io.StringIO inputs to certain modules

Push :fast_forward: to next minor release (v0.3.0):
- [ ] #412 Wrap subplot
- [ ] #471 Wrap plot3d
- [ ] #525 Add velo function

CC @GenericMappingTools/python-contributors, @lhoupert, @hemmelig, @MarkWieczorek, and anyone else interested.

**Comment by seisman** [comment]
@weiji14 The test `test_grdview_grid_file_with_region_subset` is marked as xfail, but it actually passes. You may want to check it if it really works as expected.

**Comment by weiji14** [comment]
Gonna bump this out by a day to Friday 11 Sep 2020 (UTC time). Should be possible to get #560 and #581 done today, but the release note curation will take a bit of time.

**Comment by leouieda** [comment]
@weiji14 thanks for leading the charge on this! 👏🏽  

A few suggestions to simplify this:

* You don't need to create the tag locally. When you make the GitHub release, it will make the tag automatically as well so that's one less thing to do.
* The perks of not being 1.0 yet is that we don't have to worry about backporting bug fixes to previous releases. So there is no need for a 0.1 branch, which makes things so much simpler.

**Comment by weiji14** [comment]
> @weiji14 thanks for leading the charge on this! 👏🏽

Welcome, hope you and your partner are doing well with the new little one :grin:

> A few suggestions to simplify this:
> 
> * You don't need to create the tag locally. When you make the GitHub release, it will make the tag automatically as well so that's one less thing to do.
> 
> * The perks of not being 1.0 yet is that we don't have to worry about backporting bug fixes to previous releases. So there is no need for a 0.1 branch, which makes things so much simpler.

Sounds good, we can update the [release checklist template](https://github.com/GenericMappingTools/pygmt/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md) to remove these two bullet points. Also ties in with your previous comment at https://github.com/GenericMappingTools/pygmt/pull/424#issuecomment-625747471.

**Comment by weiji14** [comment]
Ok, release time! @seisman, could you do the Github Release at https://github.com/GenericMappingTools/pygmt/releases (which will make the tag v0.2.0 as @leouieda menitoned), then I'll upload the zip file to Zenodo.

**Comment by seisman** [comment]
Done.

**Comment by weiji14** [comment]
Thanks @seisman, I see you've bumped up the PyGMT version at try-gmt (https://github.com/GenericMappingTools/try-gmt/commit/2f22696c292e7db3952b9f2c074d95556b3c198d). I've just made the PyGMT v0.2.0 release announcement on the forum at https://forum.generic-mapping-tools.org/t/pygmt-v0-2-0-released/879 too.

So what's left should be to link to that on the website, and also on ResearchGate. How about you pick one and I'll do the other?

**Comment by seisman** [comment]
OK, I'll update the website.

**Comment by weiji14** [comment]
Great, announcements all done! We can close this now and move on to the next big thing :grin:
