### ISSUE TITLE
Release PyGMT 0.2.1

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#665]
**Release**: [v0.2.1](https://github.com/GenericMappingTools/pygmt/milestone/4)
**Scheduled Date**: 2020/11/14

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version"
- [x] Update Changelog (#683)
- [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher (#683)
- [x] Update citation information https://github.com/GenericMappingTools/pygmt#citing-pygmt (#683)

**Release**:
- [x] Go to [GitHub Release](https://github.com/GenericMappingTools/pygmt/releases) and make a release, this will automatically create a tag too
- [x] Manually upload the pygmt-vX.Y.Z.zip file to https://zenodo.org/deposit, make sure you file it under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot] (https://github.com/conda-forge/pygmt-feedstock/pull/11)
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (https://github.com/GenericMappingTools/try-gmt/pull/13)
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) https://forum.generic-mapping-tools.org/t/pygmt-v0-2-1-released/1038/1
  - [ ] ~~[Major/Minor releases only] GMT [website](https://github.com/GenericMappingTools/website) (News)~~
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) 
  - [x] Twitter (https://twitter.com/leouieda/status/1328759813732405248)
---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by seisman** [comment]
It has been one and a half months since release v0.2.0. There are little code changes since v0.2.0, but we have made a lot of improvements to the documentation and add several new gallery examples. To me, it's a good time for us to have the release v0.2.1 to increase the visibility of the improved documentation.

GMT plans to release v6.2.0 in late December or early January, and we will definitely bump the minimum required GMT version to 6.2.0 in PyGMT v0.3.0. There are still two months, we probably will have another one or two patch releases before v0.3.0.

**Comment by weiji14** [comment]
> It has been one and a half months since release v0.2.0. There are little code changes since v0.2.0, but we have made a lot of improvements to the documentation and add several new gallery examples. To me, it's a good time for us to have the release v0.2.1 to increase the visibility of the improved documentation.

Thanks for taking the lead on this @seisman! Definitely time for a release, I'm quite pleased with the improved documentation, especially with Liam's video added in #643! Shall we set a date for end of October 2020?

> GMT plans to release v6.2.0 in late December or early January, and we will definitely bump the minimum required GMT version to 6.2.0 in PyGMT v0.3.0. There are still two months, we probably will have another one or two patch releases before v0.3.0.

Yep, I have a feeling we'll need a PyGMT v0.2.2 too before GMT 6.2.0 is out. We should probably document the `conda install -c conda-forge/label/dev gmt` trick in our installation steps, and #628 could be a good thing to get in if it's not too much work.

> Below is a list of issues/PRs that should be addressed before v0.2.1:
> 
>     * [ ]  How to cite PyGMT (#653)
>     * [ ]  Grdcontour's long alias for G (label_placement) is not properly documented (#622)
>     * [ ]  more?

Also:

- [ ] Complete documentation for `plot` (#666)
- [ ] Tutorial covering pygmt.config (#482)

:wave: To anyone else who's following, chip in if there's a feature you really want! E.g. I really want to sneak in `plot3d` #471 (after #666) as I need it for overlaying lines on top of a 3D grdview image at https://github.com/weiji14/deepicedrain/pull/180, but will see how we go on time.

**Comment by seisman** [comment]
Are there any issues that we need to fix before v0.2.1? What's the target date for the v0.2.1 release?

**Comment by weiji14** [comment]
Main thing left is the changelog really, waiting on https://github.com/GenericMappingTools/pygmt/pull/683#discussion_r519018998, plus an update to `doc/_static/version_switch.js` and the Zenodo BibTeX. I would set a target date for this week, say Friday 13 November?

I think we could squeeze in `velo` #525 since it's almost done. The other open PRs are mostly complicated maintenance updates that should go in the next release v0.2.2 or v0.3.0.

**Comment by seisman** [comment]
It's late for me. Feel free to finish the release.

**Comment by weiji14** [comment]
Ok, we've got Python 3.9 support and the changelog is done. @seisman, if you tag the release, I'll handle the rest (Zenodo upload and news)

**Comment by weiji14** [comment]
Alright, Zenodo DOI is up at https://doi.org/10.5281/zenodo.4253459, and the PyPI and conda-forge PyGMT packages are online! I've got a forum release announcement drafted already, just need to finish off https://github.com/GenericMappingTools/try-gmt/pull/13 first.

@GenericMappingTools/python, does anyone want to do the ResearchGate post, and shall we do a tweet as well? :wink:

**Comment by seisman** [comment]
> shall we do a tweet as well?

There is no official Twitter account for GMT yet, but see the proposal of an Instagram account (https://forum.generic-mapping-tools.org/t/1011/3).

**Comment by weiji14** [comment]
> > shall we do a tweet as well?
> 
> There is no official Twitter account for GMT yet, but see the proposal of an Instagram account (https://forum.generic-mapping-tools.org/t/1011/3).

I was actually hinting @leouieda to do a tweet for us (like https://twitter.com/leouieda/status/1305805309374590976 for PyGMT v0.2.0). An official social media account (Twitter, Instagram, etc) sounds good but let's discuss it in the meeting next week.

**Comment by leouieda** [comment]
👍 will do! Thanks all you’re doing @weiji14 and @seisman

**Comment by leouieda** [comment]
I realize it's a bit late now but just wanted to comment here for reference. This should probably have been a minor release (0.3.0) since there are new features (2 new wrapped modules + Py 3.9 + options for existing modules). The last number is mostly for plain bug fix releases or just documentation changes (no new features/enhancements). That's the basic premise of semantic versioning, at least.

**Comment by weiji14** [comment]
Thanks for making the tweet @leouieda! It really helps to spread the word outside of our GIthub bubble.

And yes, this probably should have been v0.3.0 as per semantic versioning. The 'bulk' of the release was mostly documentation changes, with new features (`plot3d` and Python 3.9 support) kinda slipped in towards the end because we 'might as well'. Will keep this in mind for the next release.
