### ISSUE TITLE
Release PyGMT v0.3.0

### ISSUE THREAD

**Issue by willschlitzer** [GenericMappingTools/pygmt#845]
**Release**: [v0.3.0](https://github.com/GenericMappingTools/pygmt/milestone/3)
**Scheduled Date**: 2021/02/15
**Pull request due date**: 2021/02/13

**Priority PRs/issues to complete prior to release**
- [x] Wrap subplot (#822)
- [x] Wrap grd2cpt (#803)
- [x] Wrap grdinfo aliases (#799)
- [x] Move plotting functions to separate modules (#808)
- [x] Add affiliation and ORCID to AUTHORS.md (#857)
- [x] Fail to install the dev version following the install instructions (#856)

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version" (@weiji14)
- [x] Update Changelog (#887) (@willschlitzer)
- [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
- [x] Update citation information https://github.com/GenericMappingTools/pygmt#citing-pygmt

**Release**:
- [x] Go to [GitHub Release](https://github.com/GenericMappingTools/pygmt/releases) and make a release, this will automatically create a tag too (@willschlitzer)
- [x] Manually upload the pygmt-vX.Y.Z.zip file to https://zenodo.org/deposit, make sure you file it under the correct reserved DOI (@weiji14)

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot] (https://github.com/conda-forge/pygmt-feedstock/pull/14)
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt (@seisman) (https://github.com/GenericMappingTools/try-gmt/commit/bd8090ce9fe07c6a083cfacfe5ae0e0a9a77b4a1)
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/) (https://forum.generic-mapping-tools.org/t/pygmt-v0-3-0-released)
  - [x] GMT [website](https://github.com/GenericMappingTools/website) (News) (@michaelgrund) (https://github.com/GenericMappingTools/website/pull/95)
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools) [link](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools/update/602b43dbfcc1e200015cbd62)
  - ~~Twitter~~ (feel free to tweet the release anyone!)

---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
Cool, cheers for taking this up @willschlitzer! This v0.3.0 seems much bigger one than the previous v0.2.1 (#665), and looking through the draft changelog at https://github.com/GenericMappingTools/pygmt/releases (viewable only to PyGMT team members), I think we might need to reduce the number of items by adding [`skip-changelog` labels](https://github.com/GenericMappingTools/pygmt/labels/skip-changelog) to trim out less important commits, particularly for the non-user facing 'maintenance' ones.

Once those last features are wrapped up (hopefully by Monday/Tuesday), please start curating a changelog (see previous one at #683), and give a shoutout if you need any help with things.

**Comment by willschlitzer** [comment]
@GenericMappingTools/python  For updating the citation info, what do I put in place for "uieda_leonardo_2020_4025418"? I'm assuming this is some sort of DOI-like reference that @leouieda set up; will it be different for the new package? Also, what is the proper order to put the authors in? I know that AUTHORS.md uses alphabetical order, but this doesn't seem to do that.

**Comment by weiji14** [comment]
> @GenericMappingTools/python  For updating the citation info, what do I put in place for "uieda_leonardo_2020_4025418"? I'm assuming this is some sort of DOI-like reference that @leouieda set up; will it be different for the new package?

I've reserved a new doi at doi.org/10.5281/zenodo.4522136, so it should be `uieda_leonardo_2021_4522136` for v0.3.0.

> Also, what is the proper order to put the authors in? I know that AUTHORS.md uses alphabetical order, but this doesn't seem to do that.

It's roughly by order of commits/lines of code/outreach contributions. Leo's definitely first since he started it, and Paul the guru is last, but the rest we can discuss in #726.

**Comment by willschlitzer** [comment]
> > @GenericMappingTools/python  For updating the citation info, what do I put in place for "uieda_leonardo_2020_4025418"? I'm assuming this is some sort of DOI-like reference that @leouieda set up; will it be different for the new package?
> 
> I've reserved a new doi at doi.org/10.5281/zenodo.4522136, so it should be `uieda_leonardo_2021_4522136` for v0.3.0.

Just so I understand it, when I upload the PyGMT zip (that's just downloading the entire repository, correct?) to Zenodo, I'll list the DOI as "10.5281/zenodo.4522136", correct?

> 
> > Also, what is the proper order to put the authors in? I know that AUTHORS.md uses alphabetical order, but this doesn't seem to do that.
> 
> It's roughly by order of commits/lines of code/outreach contributions. Leo's definitely first since he started it, and Paul the guru is last, but the rest we can discuss in #726.
I'll discuss the author order over at #726. Regarding the ORCID, it seems like I can copy everyone from the previous release, and just add myself and @michaelgrund. Is there anything else I'm forgetting?
> 
> P.S. The 12 Feb date is looking a bit too optimistic. Maybe push it out to 16 Feb or so.

Is this delay mostly because of wrapping `subplot`? I'm fine with a delay, but I do want PyGMT v0.3 done before the GMT 6.2 release. My personal preference is that it is released on 15 Feb (a US holiday) at the latest, otherwise I may have some delays during the week and not get it done until the following weekend.

**Comment by weiji14** [comment]
> Just so I understand it, when I upload the PyGMT zip (that's just downloading the entire repository, correct?) to Zenodo, I'll list the DOI as "10.5281/zenodo.4522136", correct?

Long story, but I'm actually the only one who can do the upload to Zenodo (see #601). You can still list the DOI in the changelog though.

> Is this delay mostly because of wrapping `subplot`? I'm fine with a delay, but I do want PyGMT v0.3 done before the GMT 6.2 release. My personal preference is that it is released on 15 Feb (a US holiday) at the latest, otherwise I may have some delays during the week and not get it done until the following weekend.

Ok, 15 Feb (UTC) is fine (it'll be 16 Feb for me in NZ :P). Just didn't want to overwork Dongdong over CNY ;)

**Comment by willschlitzer** [comment]
> > Just so I understand it, when I upload the PyGMT zip (that's just downloading the entire repository, correct?) to Zenodo, I'll list the DOI as "10.5281/zenodo.4522136", correct?
> 
> Yes, but I'm actually the only one who can do the upload to Zenodo (see #601). You can still list the DOI in the changelog though.

Sounds good! I'll send you the ORCIDs for @michaelgrund and me. Do you need anything else from me for this?
> 
> > Is this delay mostly because of wrapping `subplot`? I'm fine with a delay, but I do want PyGMT v0.3 done before the GMT 6.2 release. My personal preference is that it is released on 15 Feb (a US holiday) at the latest, otherwise I may have some delays during the week and not get it done until the following weekend.
> 
> Ok, 15 Feb (UTC) is fine (it'll be 16 Feb for me in NZ :P). Just didn't want to overwork Dongdong over CNY ;)
> 
>     
Sounds good!

**Comment by seisman** [comment]
15 Feb sounds a good time to me.

**Comment by seisman** [comment]
> I've reserved a new doi at doi.org/10.5281/zenodo.4522136, so it should be `uieda_leonardo_2021_4522136` for v0.3.0.

Are there any rules for the bibtex name? Is it better to use `pygmt_2021_4522136`?

**Comment by weiji14** [comment]
> > I've reserved a new doi at doi.org/10.5281/zenodo.4522136, so it should be `uieda_leonardo_2021_4522136` for v0.3.0.
> 
> Are there any rules for the bibtex name? Is it better to use `pygmt_2021_4522136`?

The `uieda_leonardo_*` name is just copied from https://zenodo.org/record/4253459/export/hx, but it's also completely arbitrary and people might change it in their reference manager anyway I guess. Using `pygmt_2021_4522136` sounds good.

**Comment by michaelgrund** [comment]
> 
> 
> > I've reserved a new doi at doi.org/10.5281/zenodo.4522136, so it should be `uieda_leonardo_2021_4522136` for v0.3.0.
> 
> Are there any rules for the bibtex name? Is it better to use `pygmt_2021_4522136`?

As @weiji14 mentioned the bibtex name is completely arbitrary, in principle it's possible to select what ever you want but I agree that `pygmt_2021_4522136`  (and for future releases `pygmt_202X_*`) would be a good choice.

**Comment by weiji14** [comment]
Ok, subplot wrapper is finally done (woohoo)! I realize there's a lot of really good documentation improvements in the pipeline, and I'm happy for one or two to sneak in, but let's not waste time with the changelog at #887.

**Comment by weiji14** [comment]
Ok, changelog merged and published at https://www.pygmt.org/dev/changes.html#release-v0-3-0-2021-02-15! @willschlitzer, once you publish the release, I'll work on the Zenodo zipfile upload, and then it'll be the post release announcements.

**Comment by weiji14** [comment]
Let's edit the forum announcement together at https://hackmd.io/@pygmt/v0-3-0_announcement. For reference, see previous one at https://forum.generic-mapping-tools.org/t/pygmt-v0-2-1-released.

**Comment by weiji14** [comment]
Argh, PyPI release isn't correct, we released https://pypi.org/project/pygmt/0.3.1.dev0/#history instead. Something wrong with the PR #679.

**Comment by seisman** [comment]
> We'll need to manually build and make a upload a PyPI release 

I just made an upload of v0.3.0 (https://pypi.org/project/pygmt/0.3.0/).

Here is the command I'm using:
```
python -m pip install setuptools wheel
python setup.py sdist bdist_wheel
twine upload dist/*
```

> I guess we could just download the 0.3.1.dev0 wheel/tar.gz and reupload it as 0.3.0?

No, we can't. The version information is written in the packages, so I need to rebuild them.

**Comment by seisman** [comment]
I haven't deleted v0.3.1.dev0 yet (https://pypi.org/project/pygmt/0.3.1.dev0/). I will delete it after you confirm that the v0.3.0 release works well.

I tried the following command, and it install PyGMT v0.3.0 correctly. So it looks good to me.
```
# cleanup the cache
python -m pip cache purge
# install PyGMT
pip install pygmt
```

**Comment by michaelgrund** [comment]
> 
> 
> Let's edit the forum announcement together at https://hackmd.io/@pygmt/v0-3-0_announcement. For reference, see previous one at https://forum.generic-mapping-tools.org/t/pygmt-v0-2-1-released.

I already added some notes, partly influenced by the previous release.

**Comment by weiji14** [comment]
> I just made an upload of v0.3.0 (https://pypi.org/project/pygmt/0.3.0/).

Phew, you're a lifesaver @seisman! Was panicking a bit with all the release drama just now!

> I haven't deleted v0.3.1.dev0 yet (https://pypi.org/project/pygmt/0.3.1.dev0/). I will delete it after you confirm that the v0.3.0 release works well.
> 
> I tried the following command, and it install PyGMT v0.3.0 correctly. So it looks good to me.
> 
> ```
> # cleanup the cache
> python -m pip cache purge
> # install PyGMT
> pip install pygmt
> ```

Yep, I checked the tar.gz file and installed the wheel. Seems pretty much the same as 0.3.1.dev0 but `pygmt.show_versions()` gives v0.3.0 (which is good!). I think we can delete the 0.3.1.dev0 from PyPI now.

**Comment by seisman** [comment]
> I think we can delete the 0.3.1.dev0 from PyPI now.

Done!

**Comment by weiji14** [comment]
> > Let's edit the forum announcement together at https://hackmd.io/@pygmt/v0-3-0_announcement. For reference, see previous one at https://forum.generic-mapping-tools.org/t/pygmt-v0-2-1-released.
> 
> I already added some notes, partly influenced by the previous release.

Thanks @michaelgrund! I see that @seisman and @liamtoney's added some sentences as well. I'll polish the notes up and post in to the GMT forum later. If someone wants to start a PR to the GMT website (see previous one at https://github.com/GenericMappingTools/website/pull/69) that would be terrific!

**Comment by michaelgrund** [comment]
> 
> 
> > > Let's edit the forum announcement together at https://hackmd.io/@pygmt/v0-3-0_announcement. For reference, see previous one at https://forum.generic-mapping-tools.org/t/pygmt-v0-2-1-released.
> > 
> > 
> > I already added some notes, partly influenced by the previous release.
> 
> Thanks @michaelgrund! I see that @seisman and @liamtoney's added some sentences as well. I'll polish the notes up and post it to the GMT forum later. If someone wants to start a PR to the GMT website (see previous one at [GenericMappingTools/website#69](https://github.com/GenericMappingTools/website/pull/69)) that would be terrific!

Added a PR with the updates for the website @weiji14 :wink:

**Comment by weiji14** [comment]
Just tried out the try-gmt demo at https://github.com/GenericMappingTools/try-gmt. Not sure why the version is showing up as v0.0.0 (pulled from conda-forge)?

![image](https://user-images.githubusercontent.com/23487320/107992754-38504500-703e-11eb-9193-220fc0a5aa86.png)

**Comment by seisman** [comment]
> Just tried out the try-gmt demo at [GenericMappingTools/try-gmt](https://github.com/GenericMappingTools/try-gmt). Not sure why the version is showing up as v0.0.0 (pulled from conda-forge)?
> 

I also noticed that. If you download and extract the tarball from conda-forge, you will see that the metadata in the package is v0.0.0.

**Comment by seisman** [comment]
> > Just tried out the try-gmt demo at [GenericMappingTools/try-gmt](https://github.com/GenericMappingTools/try-gmt). Not sure why the version is showing up as v0.0.0 (pulled from conda-forge)?
> 
> I also noticed that. If you download and extract the tarball from conda-forge, you will see that the metadata in the package is v0.0.0.

We are not alone (https://github.com/conda-forge/pint-feedstock/issues/32) 😃

**Comment by weiji14** [comment]
Ah ok, setuptools_scm again :sweat_smile:. Do you want to submit a PR based on that? I'm just polishing up the release announcement now.

**Comment by seisman** [comment]
> Do you want to submit a PR to [conda-forge/pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) based on that?

OK.

**Comment by weiji14** [comment]
Alright, conda-forge versioning issue was fixed in https://github.com/conda-forge/pygmt-feedstock/pull/15 (and @willschlitzer, we've added you as a maintainer there).

Forum announcement has also been posted on https://forum.generic-mapping-tools.org/t/pygmt-v0-3-0-released! What's left should just be the ResearchGate announcement (any takers?). Maybe twitter/instagram as well? Did we manage to set up a social media account @meghanrjones?

**Comment by seisman** [comment]
Ping @meghanrjones about the social media accounts. 

If we still don't have one, then we can close the issue.

**Comment by meghanrjones** [comment]
> Ping @meghanrjones about the social media accounts.
> 
> If we still don't have one, then we can close the issue.

I have not yet. I don't think Leo has either. I will be sure to get one set up in time for the next release (sorry, social media is not my expertise).

**Comment by liamtoney** [comment]
> > Ping @meghanrjones about the social media accounts.
> > If we still don't have one, then we can close the issue.
> 
> I have not yet. I don't think Leo has either. I will be sure to get one set up in time for the next release (sorry, social media is not my expertise).

Perhaps we could query the forum for a volunteer? Some folks really like this sort of thing (I don't have time for it)

Matplotlib has a cool Insta: https://www.instagram.com/matplotart/?hl=en. We could also set up a submission system.

**Comment by weiji14** [comment]
> Perhaps we could query the forum for a volunteer? Some folks really like this sort of thing (I don't have time for it)
> 
> Matplotlib has a cool Insta: https://www.instagram.com/matplotart/?hl=en. We could also set up a submission system.

Cool, I think we can move this discussion to another thread. I'll mark this Release v0.3.0 issue as closed, but feel free anyone to find a way to spread the word (tweet or otherwise)!

**Comment by willschlitzer** [comment]
@GenericMappingTools/python-contributors not sure why we closed this; I haven't seen sufficient evidence that the "Party" criteria have been met!

On a serious note; great team work everyone! Glad we got this done!
