### ISSUE TITLE
Release PyGMT v0.3.1

### ISSUE THREAD

**Issue by willschlitzer** [GenericMappingTools/pygmt#987]
**Release**: [v0.3.1](https://github.com/GenericMappingTools/pygmt/milestone/7)
**Scheduled Date**: 2021/03/14
**Pull request due date**: 2021/03/12

**Priority PRs/issues to complete prior to release**
@GenericMappingTools/python Any priorities to finish for this patch release?

- [x] Unnecessary files in the source distributions (#904)
- [ ] ~~Document how to skip CI in the contributing guides (#908)~~
- [x] Better categories for gallery examples (#876)
- [x] Let pygmt.info load datetime columns into a str dtype array (#960)

**Before release**:
- [x] Reserve a DOI on [Zenodo](https://zenodo.org) by clicking on "New Version"
- [x] Finish up 'Changelog entry for v0.3.1' Pull Request (#1047):
  - [x] Add a new entry in `doc/_static/version_switch.js` for documentation switcher
  - [x] Update citation information https://github.com/GenericMappingTools/pygmt#citing-pygmt
  - [x] Add the documentation link https://github.com/GenericMappingTools/pygmt#documentation-for-other-versions
  - [x] Add compatibility information https://github.com/GenericMappingTools/pygmt#compatibility-with-python-and-gmt-versions
  - [x] Copy draft changelog from Release Drafter and edit it to look nice

**Release**:
- [x] At the [PyGMT release page on GitHub](https://github.com/GenericMappingTools/pygmt/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to v0.3.1
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too
- [x] Manually upload the pygmt-v0.3.1.zip file to https://zenodo.org/deposit, ensure that it is filed under the correct reserved DOI

**After release**:
- [x] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot]
- [x] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt
- [x] Announce the release on:
  - [x] GMT [forum](https://forum.generic-mapping-tools.org/c/news/)
  - ~~[Major/Minor releases only] GMT [website](https://github.com/GenericMappingTools/website) (News)~~
  - [x] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools)
  - [x] [Twitter](https://twitter.com/gmt_dev)
---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
Alright, since we're getting close to the release date, I've moved a couple of lower priority issues from the v0.3.1 to v0.4.0 milestone. We should definitely prioritize wrapping up the gallery reorganization #876 in the next day or two (since a few other PRs depend on it). I'd encourage everyone to help out in reviewing the open PRs, and I see that quite a few people have stepped up which is good!

Afterwards, on 14 March (UTC), we'll need volunteers to help out with the following:
- [ ] Start a PR for a new Changelog entry (see previous one at #887 and instructions at https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md#making-a-release
- [ ] Draft a release announcement for the forum at https://hackmd.io/@pygmt (see previous one at https://hackmd.io/@pygmt/v0-3-0_announcement)
- [ ] Social media outreach:
  - [ ] Setup Twitter/Instagram as mentioned in the last release at https://github.com/GenericMappingTools/pygmt/issues/845#issuecomment-779489746
  - [ ] If anyone has experience with writing a blog post, that would be a great contribution too!
  - [ ] Any contributor wanting to be listed as a collaborator on [PyGMT's ResearchGate profile](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools), just ping me (or any other @GenericMappingTools/python member) and we'll get you added in.

Just raise your hand :wave: up on what you'd like to help out with and you'll get the job. No interview required.

**Comment by willschlitzer** [comment]
I'll do the change log

**Comment by core-man** [comment]
>   * [ ]  Any contributor wanting to be listed as a collaborator on [PyGMT's ResearchGate profile](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools), just ping me (or any other @GenericMappingTools/python member) and we'll get you added in.

@weiji14 I am grateful to be listed as a collaborator.

**Comment by weiji14** [comment]
> @weiji14 Do we have a Zenodo DOI yet?

Yep, the DOI for v0.3.1 will be `10.5281/zenodo.4592991`.

> @weiji14 I am grateful to be listed as a collaborator.

Cool, just followed you on ResearchGate, you'll need to follow me back for me to add you as a collaborator according to https://www.researchgate.net/post/how_can_I_add_collaborators_to_an_existing_project (Same for anyone else wanting to join).

**Comment by michaelgrund** [comment]
> 
> 
> Alright, since we're getting close to the release date, I've moved a couple of lower priority issues from the v0.3.1 to v0.4.0 milestone. We should definitely prioritize wrapping up the gallery reorganization #876 in the next day or two (since a few other PRs depend on it). I'd encourage everyone to help out in reviewing the open PRs, and I see that quite a few people have stepped up which is good!
> 
> Afterwards, on 14 March (UTC), we'll need volunteers to help out with the following:
> 
>     * [ ]  Start a PR for a new Changelog entry (see previous one at #887 and instructions at https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md#making-a-release
> 
>     * [ ]  Draft a release announcement for the forum at https://hackmd.io/@pygmt (see previous one at https://hackmd.io/@pygmt/v0-3-0_announcement)
> 
>     * [ ]  Social media outreach:
>       
>       * [ ]  Setup Twitter/Instagram as mentioned in the last release at [#845 (comment)](https://github.com/GenericMappingTools/pygmt/issues/845#issuecomment-779489746)
>       * [ ]  If anyone has experience with writing a blog post, that would be a great contribution too!
>       * [ ]  Any contributor wanting to be listed as a collaborator on [PyGMT's ResearchGate profile](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools), just ping me (or any other @GenericMappingTools/python member) and we'll get you added in.
> 
> 
> Just raise your hand 👋 up on what you'd like to help out with and you'll get the job. No interview required.

I will only be partially available on 14 March, however, if possible I could help out with updating the website etc. (as for the last release).

**Comment by meghanrjones** [comment]
> Alright, since we're getting close to the release date, I've moved a couple of lower priority issues from the v0.3.1 to v0.4.0 milestone. We should definitely prioritize wrapping up the gallery reorganization #876 in the next day or two (since a few other PRs depend on it). I'd encourage everyone to help out in reviewing the open PRs, and I see that quite a few people have stepped up which is good!
> 
> Afterwards, on 14 March (UTC), we'll need volunteers to help out with the following:
> 
>     * [ ]  Start a PR for a new Changelog entry (see previous one at #887 and instructions at https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md#making-a-release
> 
>     * [ ]  Draft a release announcement for the forum at https://hackmd.io/@pygmt (see previous one at https://hackmd.io/@pygmt/v0-3-0_announcement)
> 
>     * [ ]  Social media outreach:
>       
>       * [ ]  Setup Twitter/Instagram as mentioned in the last release at [#845 (comment)](https://github.com/GenericMappingTools/pygmt/issues/845#issuecomment-779489746)
>       * [ ]  If anyone has experience with writing a blog post, that would be a great contribution too!
>       * [ ]  Any contributor wanting to be listed as a collaborator on [PyGMT's ResearchGate profile](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools), just ping me (or any other @GenericMappingTools/python member) and we'll get you added in.
> 
> 
> Just raise your hand 👋 up on what you'd like to help out with and you'll get the job. No interview required.

Since I previously said I would, I can create a twitter account and then hopefully transfer it later on to someone who understands how to use emojis. Instagram is over my head though, sorry. Do you think GMT/PyGMT twitter should be the same or different?

**Comment by core-man** [comment]
I am available, but I am not good at social media outreach. Maybe I can help draft a release announcement for the forum at https://hackmd.io/@pygmt if it does not need any permission.

**Comment by willschlitzer** [comment]
> 
> 
> > Alright, since we're getting close to the release date, I've moved a couple of lower priority issues from the v0.3.1 to v0.4.0 milestone. We should definitely prioritize wrapping up the gallery reorganization #876 in the next day or two (since a few other PRs depend on it). I'd encourage everyone to help out in reviewing the open PRs, and I see that quite a few people have stepped up which is good!
> > Afterwards, on 14 March (UTC), we'll need volunteers to help out with the following:
> > ```
> > * [ ]  Start a PR for a new Changelog entry (see previous one at #887 and instructions at https://github.com/GenericMappingTools/pygmt/blob/master/MAINTENANCE.md#making-a-release
> > 
> > * [ ]  Draft a release announcement for the forum at https://hackmd.io/@pygmt (see previous one at https://hackmd.io/@pygmt/v0-3-0_announcement)
> > 
> > * [ ]  Social media outreach:
> >   
> >   * [ ]  Setup Twitter/Instagram as mentioned in the last release at [#845 (comment)](https://github.com/GenericMappingTools/pygmt/issues/845#issuecomment-779489746)
> >   * [ ]  If anyone has experience with writing a blog post, that would be a great contribution too!
> >   * [ ]  Any contributor wanting to be listed as a collaborator on [PyGMT's ResearchGate profile](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools), just ping me (or any other @GenericMappingTools/python member) and we'll get you added in.
> > ```
> > 
> > 
> > Just raise your hand 👋 up on what you'd like to help out with and you'll get the job. No interview required.
> 
> Since I previously said I would, I can create a twitter account and then hopefully transfer it later on to someone who understands how to use emojis. Instagram is over my head though, sorry. Do you think GMT/PyGMT twitter should be the same or different?

Unfortunately "@pygmt" on Twitter is a suspended account; I think keeping PyGMT the same as the GMT Twitter is fine for now; I don't foresee the project tweeting that often.

Also, I registered "pygmt.dev@gmail.com" (pygmt@gmail.com was too short) if we want to start up a YouTube channel for tutorials and the like.

**Comment by weiji14** [comment]
> I am available, but I am not good at social media outreach. Maybe I can help draft a release announcement for the forum at https://hackmd.io/@pygmt if it does not need any permission.

Cool, just sent a hackmd invite to you and @michaelgrund too. I think most everybody is in but let me know if anyone else wants to join.

> > Since I previously said I would, I can create a twitter account and then hopefully transfer it later on to someone who understands how to use emojis. Instagram is over my head though, sorry. Do you think GMT/PyGMT twitter should be the same or different?
> 
> Unfortunately "@pygmt" on Twitter is a suspended account; I think keeping PyGMT the same as the GMT Twitter is fine for now; I don't foresee the project tweeting that often.
> 
> Also, I registered "[pygmt.dev@gmail.com](mailto:pygmt.dev@gmail.com)" ([pygmt@gmail.com](mailto:pygmt@gmail.com) was too short) if we want to start up a YouTube channel for tutorials and the like.

Thanks @willschlitzer for setting that up! I agree that using the same twitter handle for GMT/PyGMT is fine, people can always hashtag #pygmt to be more specific. Probably easier to use the GMT YouTube channel to post PyGMT content, but I'm sure we'll find a use for that email at some point.

**Comment by meghanrjones** [comment]
We're live on twitter! https://twitter.com/gmt_software

The 'handle' has to be 4+ characters (not GMT), less than 15 characters (not GenericMappingTools), and only alphanumeric characters and underscores. I came up with @gmt_software but if anyone has better ideas please feel free to share.

**Comment by seisman** [comment]
> The 'handle' has to be 4+ characters (not GMT), less than 15 characters (not GenericMappingTools),

It's really annoying 🤦

**Comment by seisman** [comment]
> We're live on twitter! [twitter.com/gmt_software](https://twitter.com/gmt_software)
> 
> The 'handle' has to be 4+ characters (not GMT), less than 15 characters (not GenericMappingTools), and only alphanumeric characters and underscores. I came up with @gmt_software but if anyone has better ideas please feel free to share.

@meghanrjones Did you ask Leo or Paul if there is already a GMT (maybe suspended) Twitter account? I have the impression Leo may already create one.

**Comment by meghanrjones** [comment]
> > We're live on twitter! [twitter.com/gmt_software](https://twitter.com/gmt_software)
> > The 'handle' has to be 4+ characters (not GMT), less than 15 characters (not GenericMappingTools), and only alphanumeric characters and underscores. I came up with @gmt_software but if anyone has better ideas please feel free to share.
> 
> @meghanrjones Did you ask Leo or Paul if there is already a GMT (maybe suspended) Twitter account? I have the impression Leo may already create one.

I did not think this was the case but am double-checking now.

**Comment by weiji14** [comment]
> > > We're live on twitter! [twitter.com/gmt_software](https://twitter.com/gmt_software)
> > > The 'handle' has to be 4+ characters (not GMT), less than 15 characters (not GenericMappingTools), and only alphanumeric characters and underscores. I came up with @gmt_software but if anyone has better ideas please feel free to share.
> > 
> > 
> > @meghanrjones Did you ask Leo or Paul if there is already a GMT (maybe suspended) Twitter account? I have the impression Leo may already create one.
> 
> I did not think this was the case but am double-checking now.

What about `@gmt_maps`? or `@gmt_team`? Feel like `@gmt_software` is a bit of a handful to type.

**Comment by core-man** [comment]
> Made some minor changes to the hackmd draft and added a question about the correct form (is it GMT **6.2.** or GMT **6.2.0**?).

Thanks. You are right. It is GMT **6.2.0**. The highlights at https://hackmd.io/@pygmt/v0-3-1_announcement were directly copied from the changelog draft in #1047 and will be updated when that PR is merged.

**Comment by willschlitzer** [comment]
Release has been done on GitHub!

**Comment by weiji14** [comment]
And we are live on PyPI https://pypi.org/project/pygmt/0.3.1! I'll double check the package before uploading to Zenodo, got too paranoid with Murphy's Law during the last release.

**Comment by michaelgrund** [comment]
Great work!!! Thanks for all your efforts 🚀 .

**Comment by weiji14** [comment]
Good work team, I'm heading off to bed so will delegate the rest to you all. No rush to do them, please enjoy the rest of your Sunday first!

> **After release**:
> - [ ] Update conda-forge [pygmt-feedstock](https://github.com/conda-forge/pygmt-feedstock) [Usually done automatically by conda-forge's bot]

@willschlitzer, will leave this to you.

> - [ ] Bump PyGMT version on https://github.com/GenericMappingTools/try-gmt

Someone new could give this a go, see https://github.com/GenericMappingTools/try-gmt/pull/13 for an example.

> - [ ] Announce the release on:
>   - [ ] GMT [forum](https://forum.generic-mapping-tools.org/c/news/)
>   - [ ] [ResearchGate](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools)
>   - [ ] [Twitter](https://twitter.com/gmt_software)

Let's do the announcements on Monday (UTC time), I've edited the draft at https://hackmd.io/@pygmt/v0-3-1_announcement a bit (to put the new contributors up front) but definitely needs a bit more polish. @core-man, will leave it to you to post it up there when everyone's given it a thumbs up.

**Comment by michaelgrund** [comment]
> Let's do the announcements on Monday (UTC time), I've edited the draft at https://hackmd.io/@pygmt/v0-3-1_announcement a bit (to put the new contributors up front) but definitely needs a bit more polish. @core-man, will leave it to you to post it up there when everyone's given it a thumbs up.

Made some minor changes on your latest version @weiji14. Good night's sleep 😉.

**Comment by core-man** [comment]
Good **global team** work. It seems the PyGMT team is working all the time in a day. Thanks to everyone. I've learned a lot during the last several weeks.

BTW, I'm going to use some gallery and tutorial examples to give **a preliminary introduction to PyGMT** to the Seismological Group at our university (i.e., Nanyang Technological University, Singapore) next week. See a draft [tutorial repository](https://github.com/MIGG-NTU/PyGMT2021). Hope more and more GMT (bash) users know and use PyGMT :smile:.

**Comment by meghanrjones** [comment]
> > Let's do the announcements on Monday (UTC time), I've edited the draft at https://hackmd.io/@pygmt/v0-3-1_announcement a bit (to put the new contributors up front) but definitely needs a bit more polish. @core-man, will leave it to you to post it up there when everyone's given it a thumbs up.
> 
> Made some minor changes on your latest version @weiji14. Good night's sleep 😉.

I have a couple recommended changes to the draft. Is it too late for me to edit the announcement? (obligatory grumble about the U.S. time shift making this even hard to track 😫)

**Comment by core-man** [comment]
> > > Let's do the announcements on Monday (UTC time), I've edited the draft at https://hackmd.io/@pygmt/v0-3-1_announcement a bit (to put the new contributors up front) but definitely needs a bit more polish. @core-man, will leave it to you to post it up there when everyone's given it a thumbs up.
> > 
> > 
> > Made some minor changes on your latest version @weiji14. Good night's sleep 😉.
> 
> I have a couple recommended changes to the draft. Is it too late for me to edit the announcement? (obligatory grumble about the U.S. time shift making this even hard to track 😫)

Of course, please help use polish it. I am heading off to bed and see you guys tomorrow.

**Comment by meghanrjones** [comment]
> > > > We're live on twitter! [twitter.com/gmt_software](https://twitter.com/gmt_software)
> > > > The 'handle' has to be 4+ characters (not GMT), less than 15 characters (not GenericMappingTools), and only alphanumeric characters and underscores. I came up with @gmt_software but if anyone has better ideas please feel free to share.
> > > 
> > > 
> > > @meghanrjones Did you ask Leo or Paul if there is already a GMT (maybe suspended) Twitter account? I have the impression Leo may already create one.
> > 
> > 
> > I did not think this was the case but am double-checking now.
> 
> What about `@gmt_maps`? or `@gmt_team`? Feel like `@gmt_software` is a bit of a handful to type.

@gmt_team is nice! I can update it to that before making the twitter announcement unless there are any other recommendations. 

Regarding other accounts, Paul wasn't aware of any and I haven't heard back from Leo (which is good, since it's a weekend). My memory of the 2020-11-19 community meeting was that the previous attempt to create an account failed and that a new one would be necessary. The community meeting notes just say 'Twitter: Leo and Meghan can do twitter' which doesn't provide a definitive answer.

**Comment by seisman** [comment]
There is already a Twitter user called "gmt_team", which was created in Jan 2017, almost the same time that Leo started his postdoc in Hawaii. That's why I'm wondering if this "gmt_team" account was created by him.

If "gmt_team" is not available, what about "gmt_dev"?

**Comment by meghanrjones** [comment]
> There is already a Twitter user called "gmt_team", which was created in Jan 2017, almost the same time that Leo started his postdoc in Hawaii. That's why I'm wondering if this "gmt_team" account was created by him.
> 
> If "gmt_team" is not available, what about "gmt_dev"?

gmt_dev is fine too. I don't think that account is associated with Leo. The gmt_team user is only following one person who goes by GMT and is not related to the GenericMappingTools.

**Comment by seisman** [comment]
> The gmt_team user is only following one person who goes by GMT and is not related to the GenericMappingTools.

I think you're right! 

FYI, xarray and pandas also use "_dev", and numpy uses "_team" 😃 

- xarray: https://twitter.com/xarray_dev
- pandas: https://twitter.com/pandas_dev
- numpy: https://twitter.com/numpy_team

**Comment by meghanrjones** [comment]
> FYI, xarray and pandas also use "_dev", and numpy uses "_team" 😃
> 
>     * xarray: https://twitter.com/xarray_dev
> 
>     * pandas: https://twitter.com/pandas_dev
> 
>     * numpy: https://twitter.com/numpy_team

Nice! Let's go with gmt_dev, since it's available. It should be all set to go now.

**Comment by weiji14** [comment]
> Nice! Let's go with gmt_dev, since it's available. It should be all set to go now.

Wow, there's already 66 followers (and counting) at https://twitter.com/gmt_dev after the [forum announcement](https://forum.generic-mapping-tools.org/t/gmt-is-on-twitter/1461)!

> > I have a couple recommended changes to the draft. Is it too late for me to edit the announcement? (obligatory grumble about the U.S. time shift making this even hard to track tired_face)
> 
> Of course, please help polish it. I am heading off to bed and see you guys tomorrow.

Did another round of editing the draft at https://hackmd.io/@pygmt/v0-3-1_announcement. I'd appreciate a bit more proof-reading, and would prefer it if someone else does the posts it this time (literally just copying and pasting the markdown into a box!). We can then do the ResearchGate and Twitter announcement after.

**Comment by meghanrjones** [comment]
> > Nice! Let's go with gmt_dev, since it's available. It should be all set to go now.
> 
> Wow, there's already 66 followers (and counting) at https://twitter.com/gmt_dev after the [forum announcement](https://forum.generic-mapping-tools.org/t/gmt-is-on-twitter/1461)!
> 
> > > I have a couple recommended changes to the draft. Is it too late for me to edit the announcement? (obligatory grumble about the U.S. time shift making this even hard to track tired_face)
> > 
> > 
> > Of course, please help polish it. I am heading off to bed and see you guys tomorrow.
> 
> Did another round of editing the draft at https://hackmd.io/@pygmt/v0-3-1_announcement. I'd appreciate a bit more proof-reading, and would prefer it if someone else does the forum post it this time (literally just copying and pasting the markdown into a box!). We can then do the ResearchGate and Twitter announcement after.

I can do the forum post. I did not really understand this statement in the announcement - ``version v0.3.1, a release with more than a handful of new gallery examples``. Is this stating that the number of new gallery examples is more than a handful or that the release includes more than just new gallery examples?

**Comment by meghanrjones** [comment]
One other question about the forum announcement - would it be better for the highlights to link to the new pages rather than the PRs? The PRs can be found in the changelog and I expect that forum readers might be more interested in the product rather than the process.

**Comment by weiji14** [comment]
> I can do the forum post. I did not really understand this statement in the announcement - `version v0.3.1, a release with more than a handful of new gallery examples`. Is this stating that the number of new gallery examples is more than a handful or that the release includes more than just new gallery examples?

Cool, please do make the post! We do have a more than 5 new gallery examples, and that's what I meant by a handful, but probably nice if we can rephrase it a bit (feel free to make the change).

> One other question about the forum announcement - would it be better for the highlights to link to the new pages rather than the PRs? The PRs can be found in the changelog and I expect that forum readers might be more interested in the product rather than the process.

Good idea. Those were just copied from the [highlights section in the changelog](https://www.pygmt.org/v0.3.1/changes.html#highlights), but you're right that we could just link to the output (though not sure what to do about the point on #995).

**Comment by meghanrjones** [comment]
> > I can do the forum post. I did not really understand this statement in the announcement - `version v0.3.1, a release with more than a handful of new gallery examples`. Is this stating that the number of new gallery examples is more than a handful or that the release includes more than just new gallery examples?
> 
> Cool, please do make the post! We do have a more than 5 new gallery examples, and that's what I meant by a handful, but probably nice if we can rephrase it a bit (feel free to make the change).
> 
> > One other question about the forum announcement - would it be better for the highlights to link to the new pages rather than the PRs? The PRs can be found in the changelog and I expect that forum readers might be more interested in the product rather than the process.
> 
> Good idea. Those were just copied from the [highlights section in the changelog](https://www.pygmt.org/v0.3.1/changes.html#highlights), but you're right that we could just link to the output (though not sure what to do about the point on #995).

OK, I made some changes but feel free to change it back if you prefer.  Do you have a preference for whether the forum and twitter announcements are made tonight or tomorrow morning (EST | UTC-4)?

**Comment by weiji14** [comment]
> OK, I made some changes but feel free to change it back if you prefer. 

Cool, I noticed you added back most `@username` links to GitHub. More just a minor point, but most of us have the same Github handle as on the GMT forum (myself @weiji14 included) and we could just use plain `@someone` instead of `[@someone](https://github.com/someone)`.

> Do you have a preference for whether the forum and twitter announcements are made tonight or tomorrow morning (EST | UTC-4)?

Let's do the forum announcement now. I can do the twitter announcement if you want (coordinate on the Slack channel), and I think @core-man should do the ResearchGate announcement.

**Comment by meghanrjones** [comment]
> > OK, I made some changes but feel free to change it back if you prefer.
> 
> Cool, I noticed you added back most `@username` links to GitHub. More just a minor point, but most of us have the same Github handle as on the GMT forum (myself @weiji14 included) and we could just use plain `@someone` instead of `[@someone](https://github.com/someone)`.

🤦 Good to know. Would it be better for me to change them back now?

> > Do you have a preference for whether the forum and twitter announcements are made tonight or tomorrow morning (EST | UTC-4)?
> 
> Let's do the forum announcement now. I can do the twitter announcement if you want (coordinate on the Slack channel), and I think @core-man should do the ResearchGate announcement.

Sounds good.

**Comment by meghanrjones** [comment]
Forum announcement is [posted](https://forum.generic-mapping-tools.org/t/pygmt-v0-3-1-released/1462)!

**Comment by core-man** [comment]
The announcement is great. Thanks for the revisions @meghanrjones.

**Comment by core-man** [comment]
ResearchGate announcement is [posted](https://www.researchgate.net/project/PyGMT-A-Python-interface-for-the-Generic-Mapping-Tools).

**Comment by seisman** [comment]
We have finished the v0.3.1 release! Great work! 🎉
